import { describe as suite, it, expect } from "vitest";

import { multipleRegression } from "../regression-multiple";

// Multiple (OLS) linear regression pinned against statsmodels.api.OLS on a fixed
// dataset (two predictors with mild correlation so the VIF is meaningful, about
// 3.54, but not pathological). Reference values from statsmodels 0.14 via
// OLS(y, sm.add_constant([x1, x2])).fit(), generated by
// scripts/gen-datahub-stats-golden.py:
//   intercept b0 = 1.0135   x1 slope b1 = 1.7644   x2 slope b2 = 0.7415
//   SE: b0 = 0.4028  b1 = 0.0950  b2 = 0.0885
//   t:  b1 = 18.5712  b2 = 8.3746
//   p:  b1 = 1.744e-8  b2 = 1.533e-5
//   R2 = 0.9963   adjusted R2 = 0.9954   residual SE = 0.6036
//   F(2, 9) = 1201.8155 (p = 1.183e-11)   log-likelihood = -9.2439
//   VIF (both predictors) = 3.5424
//   95% CI b1 = [1.5495, 1.9793]   95% CI b2 = [0.5412, 0.9417]
//   standardized beta1 = 0.7116   beta2 = 0.3209
const X1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
const X2 = [2, 5, 3, 8, 4, 9, 6, 11, 7, 13, 10, 14];
const Y = [4.1, 7.8, 8.9, 13.2, 13.0, 18.7, 18.2, 24.1, 22.0, 28.9, 27.1, 32.0];

suite("multiple linear regression vs statsmodels OLS", () => {
  const r = multipleRegression(
    X1.map((v, i) => [v, X2[i]]),
    Y,
    ["x1", "x2"],
  );

  it("solves the normal equations for the coefficients", () => {
    if (!r.ok) throw new Error(`expected ok, got ${(r as { error: string }).error}`);
    expect(r.intercept.estimate).toBeCloseTo(1.0135, 4);
    expect(r.slopes[0].estimate).toBeCloseTo(1.7644, 4);
    expect(r.slopes[1].estimate).toBeCloseTo(0.7415, 4);
  });

  it("matches the coefficient standard errors", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.intercept.standardError).toBeCloseTo(0.4028, 4);
    expect(r.slopes[0].standardError).toBeCloseTo(0.095, 4);
    expect(r.slopes[1].standardError).toBeCloseTo(0.0885, 4);
  });

  it("matches the t statistics and two-sided p-values", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.slopes[0].t).toBeCloseTo(18.5712, 3);
    expect(r.slopes[1].t).toBeCloseTo(8.3746, 3);
    expect(r.slopes[0].pValue).toBeCloseTo(1.743976e-8, 10);
    expect(r.slopes[1].pValue).toBeCloseTo(1.532892e-5, 8);
  });

  it("matches the 95% confidence intervals", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.slopes[0].ci95[0]).toBeCloseTo(1.5495, 3);
    expect(r.slopes[0].ci95[1]).toBeCloseTo(1.9793, 3);
    expect(r.slopes[1].ci95[0]).toBeCloseTo(0.5412, 3);
    expect(r.slopes[1].ci95[1]).toBeCloseTo(0.9417, 3);
  });

  it("matches R-squared, adjusted R-squared, and the residual SE", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.rSquared).toBeCloseTo(0.9963, 4);
    expect(r.adjRSquared).toBeCloseTo(0.9954, 4);
    expect(r.residualSE).toBeCloseTo(0.6036, 4);
  });

  it("matches the overall F statistic, its df, and p-value", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.fDfNum).toBe(2);
    expect(r.fDfDen).toBe(9);
    expect(r.fStatistic).toBeCloseTo(1201.8155, 3);
    expect(r.fPValue).toBeCloseTo(1.18272e-11, 14);
  });

  it("matches the Gaussian log-likelihood", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.logLikelihood).toBeCloseTo(-9.2439, 3);
  });

  it("matches the standardized betas and the per-predictor VIF", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.slopes[0].standardizedBeta).toBeCloseTo(0.7116, 4);
    expect(r.slopes[1].standardizedBeta).toBeCloseTo(0.3209, 4);
    expect(r.slopes[0].vif).toBeCloseTo(3.5424, 4);
    expect(r.slopes[1].vif).toBeCloseTo(3.5424, 4);
    // The intercept has no standardized beta or VIF.
    expect(Number.isNaN(r.intercept.standardizedBeta)).toBe(true);
    expect(Number.isNaN(r.intercept.vif)).toBe(true);
  });
});

suite("multiple regression input guards", () => {
  it("rejects fewer than 2 predictors", () => {
    const r = multipleRegression(
      [1, 2, 3, 4, 5].map((x) => [x]),
      [1, 2, 3, 4, 5],
    );
    expect(r.ok).toBe(false);
  });

  it("rejects too few rows to fit (n must exceed k + 1)", () => {
    const r = multipleRegression(
      [
        [1, 2],
        [3, 4],
      ],
      [1, 2],
    );
    expect(r.ok).toBe(false);
  });

  it("rejects perfectly collinear predictors (singular design)", () => {
    // x2 = 2*x1, so the design matrix is rank-deficient.
    const r = multipleRegression(
      [1, 2, 3, 4, 5, 6].map((x) => [x, 2 * x]),
      [1, 2, 3, 4, 5, 6],
    );
    expect(r.ok).toBe(false);
  });

  it("drops rows with a non-finite predictor or response", () => {
    const r = multipleRegression(
      [
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [Number.NaN, 6],
        [6, 7],
      ],
      [3, 5, 7, 9, 11, 13],
    );
    if (!r.ok) throw new Error("expected ok");
    // The NaN row is dropped, leaving 5 clean rows.
    expect(r.n).toBe(5);
  });
});
