import { describe as suite, it, expect } from "vitest";

import { logisticRegression } from "../regression-logistic";

// Binary logistic regression pinned against statsmodels.api.Logit on a fixed
// moderate-overlap dataset (no perfect separation, so the MLE converges cleanly).
// Reference values from statsmodels 0.14 via Logit(...).fit(method="newton") and
// scikit-learn roc_auc_score, generated by scripts/gen-datahub-stats-golden.py:
//   intercept b0 = -2.271    slope b1 = 0.5529
//   interceptSE  = 1.2487    slopeSE  = 0.2464
//   interceptP   = 0.069     slopeP   = 0.0248
//   oddsRatio    = 1.7383    OR CI95  = [1.0724, 2.8176]
//   logLik       = -9.5615   nullLogLik = -13.4602   mcFaddenR2 = 0.2896
//   xAtHalf      = 4.1074    auc = 0.8438            iterations = 6 (statsmodels)
const LOGIT_X = [
  0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5,
  8.0, 8.5, 9.0, 9.5, 10.0,
];
const LOGIT_Y = [
  0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
];

suite("simple logistic regression vs statsmodels Logit", () => {
  const r = logisticRegression(
    LOGIT_X.map((x) => [x]),
    LOGIT_Y,
    ["x"],
  );

  it("converges to the MLE coefficients", () => {
    if (!r.ok) throw new Error(`expected ok, got ${(r as { error: string }).error}`);
    expect(r.intercept.estimate).toBeCloseTo(-2.271, 3);
    expect(r.slope.estimate).toBeCloseTo(0.5529, 3);
  });

  it("matches the coefficient standard errors", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.intercept.standardError).toBeCloseTo(1.2487, 3);
    expect(r.slope.standardError).toBeCloseTo(0.2464, 3);
  });

  it("matches the Wald two-sided p-values", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.intercept.pValue).toBeCloseTo(0.069, 3);
    expect(r.slope.pValue).toBeCloseTo(0.0248, 3);
  });

  it("matches the odds ratio and its 95% CI", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.oddsRatio).toBeCloseTo(1.7383, 3);
    expect(r.oddsRatioCI95[0]).toBeCloseTo(1.0724, 3);
    expect(r.oddsRatioCI95[1]).toBeCloseTo(2.8176, 3);
  });

  it("matches the log-likelihood, null log-likelihood, and McFadden pseudo-R2", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.logLikelihood).toBeCloseTo(-9.5615, 3);
    expect(r.nullLogLikelihood).toBeCloseTo(-13.4602, 3);
    expect(r.mcFaddenR2).toBeCloseTo(0.2896, 4);
  });

  it("reports X at P=0.5 and the ROC AUC", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.xAtHalf).toBeCloseTo(4.1074, 3);
    expect(r.auc).toBeCloseTo(0.8438, 4);
  });

  it("converges in a small number of IRLS iterations", () => {
    if (!r.ok) throw new Error("expected ok");
    expect(r.iterations).toBeGreaterThan(0);
    expect(r.iterations).toBeLessThan(20);
  });
});

suite("logistic regression input guards", () => {
  it("rejects an all-zero (or all-one) outcome with no information to fit", () => {
    const r = logisticRegression(
      [1, 2, 3, 4, 5].map((x) => [x]),
      [0, 0, 0, 0, 0],
    );
    expect(r.ok).toBe(false);
  });

  it("rejects a non-binary Y by dropping its rows", () => {
    const r = logisticRegression(
      [1, 2, 3].map((x) => [x]),
      [0, 2, 1],
    );
    // Two rows survive (y in {0,1}), below the minimum to fit, so it fails clean.
    expect(r.ok).toBe(false);
  });
});
