// Loro Phase 3, chunk 3: the encrypted relay provider.
//
// PURPOSE. loro-codemirror handles doc<->editor binding but does NOT include any
// network layer. This module IS that network layer. It wires a local LoroDoc +
// EphemeralStore to an injected CollabTransport by:
//   - Subscribing to doc.subscribeLocalUpdates and ephemeral.subscribeLocalUpdates
//     to encrypt+sign every outgoing update with sealFrame (chunk 2) before handing
//     it to the transport.
//   - Installing transport.onMessage to open+verify every inbound frame and deliver
//     doc updates via doc.import and ephemeral updates via ephemeral.apply.
//   - Re-broadcasting a full doc state snapshot on transport.onOpen so a freshly
//     connected peer can catch up without a persistent relay server.
//
// ECHO LOOP GUARD. The Loro docs say subscribeLocalUpdates fires on "local edits"
// only (the second example in the d.ts is the canonical two-way-sync pattern that
// would be infinite if import() triggered the sub). This is confirmed by the API
// name and the official example: loro1.subscribeLocalUpdates fires on loro1's own
// commits; loro2.import(update) does NOT fire loro2.subscribeLocalUpdates. We rely
// on this guarantee and do NOT add an "applying remote" suppression flag. If a
// future Loro version changes this behavior, add a boolean guard and set it around
// every doc.import / ephemeral.apply call.
//
// TRANSPORT INTERFACE. CollabTransport is a thin abstraction over a WebSocket.
// Chunk 4 adapts a real ws.WebSocket to it. The provider never touches WebSocket
// directly, so these tests run entirely in-process with no real network.
//
// React-free. No storage. No DOM.

import { LoroDoc, EphemeralStore } from "loro-crdt";
import { sealFrame, openFrame } from "./envelope";

// ---------------------------------------------------------------------------
// CollabTransport interface.
// ---------------------------------------------------------------------------

/**
 * A thin transport abstraction the provider uses. Chunk 4 wraps a real
 * WebSocket into this shape. The provider never references WebSocket directly,
 * which keeps the unit tests free of any network dependency.
 *
 * Lifecycle contract:
 *   - send() is called only while the transport is open; the implementation
 *     may queue or discard silently if called before open.
 *   - onMessage / onOpen are called once each by the provider at construction
 *     to register its callbacks; the transport invokes those callbacks as
 *     events arrive.
 *   - close() tears down the underlying connection and no further callbacks
 *     will fire after it returns (or equivalent best-effort for async transports).
 */
export interface CollabTransport {
  send(frame: Uint8Array): void;
  onMessage(cb: (frame: Uint8Array) => void): void;
  onOpen(cb: () => void): void;
  close(): void;
}

// ---------------------------------------------------------------------------
// CollabProviderOptions.
// ---------------------------------------------------------------------------

export interface CollabProviderOptions {
  /** The local Loro document to sync. */
  doc: LoroDoc;
  /** The EphemeralStore carrying cursor/presence data (loro-codemirror drives it). */
  ephemeral: EphemeralStore;
  /** 32-byte per-session symmetric key K (generated by the initiator, wrapped via wrapSessionKey). */
  sessionKey: Uint8Array;
  /** Opaque session identifier (max 255 UTF-8 bytes). Addresses the relay room. */
  sessionId: string;
  /** This peer's Ed25519 signing private key (32 bytes). */
  senderEd25519SecretKey: Uint8Array;
  /** This peer's Ed25519 signing public key (32 bytes). Carried in every outbound frame. */
  senderEd25519PublicKey: Uint8Array;
  /**
   * The collaborating peer's Ed25519 public key, pinned from the invite.
   * When provided, any inbound frame whose senderPubKey does not match is silently
   * dropped, preventing frames from unexpected third parties.
   * Leave undefined only in tests that don't care about sender pinning.
   */
  expectedPeerEd25519PublicKey?: Uint8Array;
  /** The transport that carries encrypted frames to/from the relay. */
  transport: CollabTransport;
  /**
   * Called the FIRST TIME a remote peer's doc commit arrives via doc.import.
   *
   * Receives the Loro PeerID string and the sender's Ed25519 public key bytes
   * so the caller can record the peer -> identity mapping in the actors map
   * (Phase 3 chunk 5b). Fires at most once per remote peer per provider
   * instance. Best-effort: errors from this callback are caught and logged.
   */
  onFirstRemotePeer?: (peerId: string, senderPubKey: Uint8Array) => void;
}

// ---------------------------------------------------------------------------
// createCollabProvider.
// ---------------------------------------------------------------------------

export interface CollabProvider {
  /** Unsubscribe from doc/ephemeral and close the transport. */
  destroy(): void;
}

/**
 * Wire a local LoroDoc + EphemeralStore to a CollabTransport through the
 * encrypted+signed frame envelope.
 *
 * Subscribes to local updates, installs the inbound message handler, and
 * re-broadcasts a full doc snapshot when the transport connects so the peer
 * can catch up (the "connected peer re-broadcasts" MVP fallback).
 *
 * Returns a handle whose destroy() cleans up all subscriptions and closes the
 * transport. Call destroy() when the collab session ends.
 */
export function createCollabProvider(opts: CollabProviderOptions): CollabProvider {
  const {
    doc,
    ephemeral,
    sessionKey,
    sessionId,
    senderEd25519SecretKey,
    senderEd25519PublicKey,
    expectedPeerEd25519PublicKey,
    transport,
    onFirstRemotePeer,
  } = opts;

  // Track which remote peer IDs we have already reported to onFirstRemotePeer
  // so the callback fires at most once per peer per provider instance.
  const reportedRemotePeers = new Set<string>();

  // The local peer's own PeerID string. Remote peers have different IDs.
  // Captured once at construction so we can filter it out in the first-commit
  // subscription without calling doc.peerIdStr inside a hot callback.
  const localPeerIdStr: string = doc.peerIdStr;

  // Shared sealFrame parameters for this provider instance.
  const sealParams = {
    sessionKey,
    sessionId,
    senderEd25519SecretKey,
    senderEd25519PublicKey,
  };

  // Subscribe to local doc commits. Every local edit produces incremental update
  // bytes here; we seal them and send.
  //
  // WHY subscribeLocalUpdates does NOT need an echo guard: the Loro API guarantees
  // this fires only for locally-originated commits, not for doc.import() of remote
  // updates. See the module header for the full explanation.
  const unsubDoc = doc.subscribeLocalUpdates((bytes: Uint8Array) => {
    const frame = sealFrame({ ...sealParams, kind: "doc", plaintext: bytes });
    transport.send(frame);
  });

  // Subscribe to local ephemeral changes (cursor, presence). EphemeralStore's
  // subscribeLocalUpdates fires when this peer calls .set() directly and encodes
  // the changed keys into bytes; remote .apply() does not fire it.
  const unsubEphemeral = ephemeral.subscribeLocalUpdates((bytes: Uint8Array) => {
    const frame = sealFrame({ ...sealParams, kind: "ephemeral", plaintext: bytes });
    transport.send(frame);
  });

  // Handle inbound frames from the relay. The relay fans raw bytes; we verify and
  // decrypt each one before touching the doc or ephemeral store.
  transport.onMessage((rawFrame: Uint8Array) => {
    const opened = openFrame({
      sessionKey,
      frame: rawFrame,
      expectedSenderPublicKey: expectedPeerEd25519PublicKey,
    });

    // Drop any frame that fails signature verification, AEAD, sender mismatch, or
    // parse errors. openFrame returns null for all failure modes; we never crash
    // and we never apply tampered data.
    if (!opened) return;

    if (opened.kind === "doc") {
      // Phase 3 chunk 5b: detect new remote peers by comparing the peer set
      // before and after doc.import. We use ImportStatus.success (the map of
      // peer ids the import carried) rather than subscribeFirstCommitFromPeer,
      // because that API fires only on LOCAL commits, not on doc.import calls.
      //
      // Snapshot the known peer ids BEFORE the import. We only report a peer
      // once per provider instance (reportedRemotePeers guards re-firing).
      const knownPeersBefore = onFirstRemotePeer
        ? new Set<string>(doc.getAllChanges().keys())
        : null;

      // CRDT-merge the remote update. Idempotent: re-applying an already-known
      // update is a no-op in Loro. Does NOT fire our doc subscribeLocalUpdates.
      const status = doc.import(opened.plaintext);

      // After the import, check ImportStatus.success for any peer IDs that
      // were NOT known before the import and are NOT the local peer.
      if (onFirstRemotePeer && knownPeersBefore !== null) {
        for (const [peerId] of status.success) {
          if (peerId === localPeerIdStr) continue;
          if (knownPeersBefore.has(peerId)) continue;
          if (reportedRemotePeers.has(peerId)) continue;
          reportedRemotePeers.add(peerId);
          try {
            onFirstRemotePeer(peerId, opened.senderEd25519PublicKey);
          } catch (err) {
            console.warn("[relay-provider] onFirstRemotePeer callback threw:", err);
          }
        }
      }
    } else {
      // Deliver cursor/presence bytes to the local ephemeral store.
      ephemeral.apply(opened.plaintext);
    }
  });

  // On connect, broadcast our full doc state so the just-connected peer can catch
  // up. The MVP has no server-side persistence: if a peer was offline it missed
  // updates, so whoever is already connected re-broadcasts their snapshot here.
  // Both peers do this on their own onOpen, so the handshake is symmetric.
  //
  // We export from version zero (full update), not a version-vector diff, because
  // we have no way to know what the peer already has. Loro merges are idempotent
  // so sending already-known ops is safe and cheap.
  transport.onOpen(() => {
    const snapshot = doc.export({ mode: "update" });
    const frame = sealFrame({ ...sealParams, kind: "doc", plaintext: snapshot });
    transport.send(frame);
  });

  return {
    destroy() {
      unsubDoc();
      unsubEphemeral();
      transport.close();
    },
  };
}
