"use client";

/**
 * F2 (Onboarding v4 §6.14 Purchases redesign 2026-05-22, Purchases
 * manager): read-only fullscreen overlay that renders Alex's
 * (`demo-data/users/alex/...`) purchases page on top of the user's
 * real app.
 *
 * Why an overlay, not a route change:
 *   The tour controller's step state lives in React refs + reducer
 *   state, so a router push to a different route would unmount the
 *   controller's children and lose the tour position. By rendering as a
 *   `position: fixed` overlay over the user's `/purchases` page, the
 *   URL doesn't change, the controller stays mounted, and the back-to-
 *   real button just unmounts the overlay — the tour resumes in place.
 *
 * Data source:
 *   The demo lab fixtures live in `frontend/public/demo-data/users/alex/`
 *   (already generated by `scripts/generate-demo-data.mjs` and served
 *   statically; wikiCapture mode already reads from the same path). We
 *   fetch the JSON files at runtime, no zip extraction needed. Only
 *   alex's tasks (task_type=purchase), projects, purchase_items, and
 *   shared funding accounts are read.
 *
 * Read-only contract:
 *   - No save handlers wired up.
 *   - No API writes — the data shapes hydrated here never get fed back
 *     into `purchasesApi.*`.
 *   - The category-filter chips, time-range select, breakdown lens
 *     toggle inside SpendingDashboard remain interactive (they're
 *     pure-UI state) so the user can click around and see the charts
 *     update. This is part of what makes the demo "feel real".
 *   - "Back to my page" button in the top-right dismisses the overlay
 *     via the `onClose` callback.
 *
 * Tour cursor compatibility:
 *   - The viewer's root carries `data-tour-target="demo-purchases-viewer"`
 *     so the v4 walkthrough's `purchases-demo-charts` cursor script can
 *     locate the scrollable surface and animate scrolls to specific
 *     dashboard sections.
 *   - The SpendingDashboard heading carries
 *     `data-tour-target="demo-spending-dashboard"` for cursor anchor
 *     targeting.
 *   - The dismiss button carries
 *     `data-tour-target="demo-purchases-back-button"` so the page-lock
 *     allow-list in `purchases-back-to-real` can let the user click it.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useEscapeToClose } from "@/hooks/useEscapeToClose";
import SpendingDashboard from "@/components/SpendingDashboard";
import { resolveFundingAccountId } from "@/lib/funding/prefill";
import {
  MISC_CATEGORY_LABEL,
  isMiscProject,
} from "@/lib/purchases/misc-project";
import type {
  PurchaseItem,
  Task,
  Project,
  FundingAccount,
} from "@/lib/types";

interface DemoPurchasesViewerProps {
  /** Mount the overlay when true. When false the component returns null
   *  so it can be left mounted under a tour controller that conditionally
   *  toggles visibility without re-fetching the fixture data on every
   *  re-show. */
  open: boolean;
  /** Called when the user clicks the dismiss button. The tour
   *  controller's `purchases-back-to-real` step listens for this signal
   *  via its `branchOn` completion. */
  onClose: () => void;
  /** Optional fixture-base override for tests — the production path is
   *  `/demo-data` (served statically from `frontend/public/demo-data`).
   *  Tests pass a `data:` URL or an `http://localhost` fixture server
   *  base when the real fixtures aren't on disk. */
  fixtureBase?: string;
}

/** Demo-lab username we render. The fixtures contain alex + morgan; the
 *  brief calls for alex specifically (more populous purchase history). */
const DEMO_USERNAME = "alex";

/**
 * Counter shape on disk: `users/<u>/_counters.json` reports e.g.
 * `{"tasks":30, "projects":4, "purchase_items":20, ...}`. The viewer
 * uses these counts to drive the fetch loops (one JSON per id from
 * 1..count). Fields we read are optional on the type because tests can
 * provide minimal fixtures.
 */
interface DemoCounters {
  tasks?: number;
  projects?: number;
  purchase_items?: number;
  funding_accounts?: number;
}

/**
 * Hydrate alex's data into the shapes `SpendingDashboard` expects.
 *
 * Returns null while loading so the viewer can show a spinner. Errors
 * resolve into the loaded state with empty arrays — the viewer's empty-
 * state copy fires, which is still better than wedging the tour.
 */
async function fetchAlexFixtures(fixtureBase: string): Promise<{
  tasks: Task[];
  projects: Project[];
  purchaseItems: Array<PurchaseItem & { owner: string }>;
  fundingAccounts: FundingAccount[];
}> {
  const base = `${fixtureBase}/users/${DEMO_USERNAME}`;
  const labBase = `${fixtureBase}/users/lab`;

  // 1. Counters file gates the per-entity range fetches.
  let counters: DemoCounters = {};
  try {
    const cRes = await fetch(`${base}/_counters.json`);
    if (cRes.ok) counters = (await cRes.json()) as DemoCounters;
  } catch (err) {
    console.warn("[DemoPurchasesViewer] counters fetch failed:", err);
  }

  const projectCount = counters.projects ?? 0;
  const taskCount = counters.tasks ?? 0;
  const itemCount = counters.purchase_items ?? 0;

  // Generic fetch loop that catches per-file misses (a 404 on a single
  // id shouldn't wedge the entire dataset). Returns the union of every
  // successful parse.
  async function fetchRange<T>(
    dir: string,
    n: number,
    extraIds: number[] = [],
  ): Promise<T[]> {
    const ids = [...Array.from({ length: n }, (_, i) => i + 1), ...extraIds];
    const settled: Array<T | null> = await Promise.all(
      ids.map(async (id): Promise<T | null> => {
        try {
          const res = await fetch(`${dir}/${id}.json`);
          if (!res.ok) return null;
          return (await res.json()) as T;
        } catch {
          return null;
        }
      }),
    );
    return settled.filter((v): v is T => v !== null);
  }

  const [projectsRaw, tasksRaw, itemsRaw, fundingRaw] = await Promise.all([
    fetchRange<Project>(`${base}/projects`, projectCount),
    fetchRange<Task>(`${base}/tasks`, taskCount),
    fetchRange<PurchaseItem>(`${base}/purchase_items`, itemCount),
    // Funding accounts live under the shared lab namespace in the demo
    // fixtures (`users/lab/funding_accounts/*.json`). We seed a small
    // explicit list of ids because the lab _counters.json isn't always
    // available in the fixture set we ship.
    fetchRange<FundingAccount>(
      `${labBase}/funding_accounts`,
      counters.funding_accounts ?? 3,
    ),
  ]);

  // Decorate everything with `owner: alex` so the composite-key logic in
  // SpendingDashboard + the page surface keyed lookups against
  // `${owner}:${id}`. Purchase items carry the same owner so the
  // breakdown lens resolves project ids cleanly.
  const projects: Project[] = projectsRaw.map((p) => ({
    ...p,
    owner: DEMO_USERNAME,
    shared_with: p.shared_with ?? [],
  }));
  const tasks: Task[] = tasksRaw.map((t) => ({
    ...t,
    owner: DEMO_USERNAME,
    shared_with: t.shared_with ?? [],
    method_attachments: t.method_attachments ?? [],
    method_ids: t.method_ids ?? [],
  }));
  const fundingAccounts: FundingAccount[] = fundingRaw;
  const purchaseItems: Array<PurchaseItem & { owner: string }> = itemsRaw.map(
    (item) => ({
      ...item,
      owner: DEMO_USERNAME,
      total_price:
        item.total_price ??
        (item.price_per_unit ?? 0) * item.quantity + (item.shipping_fees ?? 0),
      vendor: item.vendor ?? null,
      category: item.category ?? null,
      // Demo fixtures are static and never migrated, so resolve the funding FK
      // live from the label here (funding-rework: SpendingDashboard groups spend
      // by funding_account_id). Keeps a pre-existing id if the fixture has one.
      funding_account_id:
        item.funding_account_id ??
        resolveFundingAccountId(item.funding_string, fundingAccounts),
    }),
  );

  return { tasks, projects, purchaseItems, fundingAccounts };
}

export default function DemoPurchasesViewer({
  open,
  onClose,
  fixtureBase = "/demo-data",
}: DemoPurchasesViewerProps) {
  const [mounted, setMounted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<{
    tasks: Task[];
    projects: Project[];
    purchaseItems: Array<PurchaseItem & { owner: string }>;
    fundingAccounts: FundingAccount[];
  } | null>(null);
  const scrollContainerRef = useRef<HTMLDivElement | null>(null);

  // Escape closes this viewer (app-wide convention). Only bound while open.
  useEscapeToClose(onClose, open);

  // One-shot mount detection so createPortal has a target (mirrors the
  // pattern in TourPageLock + InputLockOverlay).
  useEffect(() => {
    setMounted(true);
  }, []);

  // Re-fetch each time the viewer opens so a long-running session that
  // re-enters the demo after a feature flag flip sees fresh data.
  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    setLoading(true);
    void (async () => {
      try {
        const fixtures = await fetchAlexFixtures(fixtureBase);
        if (!cancelled) {
          setData(fixtures);
        }
      } catch (err) {
        console.error("[DemoPurchasesViewer] fixture load failed:", err);
        if (!cancelled) {
          setData({
            tasks: [],
            projects: [],
            purchaseItems: [],
            fundingAccounts: [],
          });
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [open, fixtureBase]);

  // Filter to purchase tasks only — matches `/purchases` page.tsx.
  const purchaseTasks = useMemo(
    () => (data?.tasks ?? []).filter((t) => t.task_type === "purchase"),
    [data?.tasks],
  );

  // Group items by composite key, same as the real page.
  const purchasesByTask = useMemo(() => {
    const map: Record<string, PurchaseItem[]> = {};
    for (const p of data?.purchaseItems ?? []) {
      const key = `${p.owner}:${p.task_id}`;
      if (!map[key]) map[key] = [];
      map[key].push(p);
    }
    return map;
  }, [data?.purchaseItems]);

  const sortedTasks = useMemo(
    () =>
      [...purchaseTasks].sort((a, b) =>
        b.start_date.localeCompare(a.start_date),
      ),
    [purchaseTasks],
  );

  const grandTotal = useMemo(
    () =>
      (data?.purchaseItems ?? []).reduce(
        (sum, p) => sum + (p.total_price ?? 0),
        0,
      ),
    [data?.purchaseItems],
  );

  if (!open || !mounted) return null;

  return createPortal(
    <div
      data-testid="demo-purchases-viewer"
      data-tour-target="demo-purchases-viewer"
      // z-index: above the input-lock overlay (419/420 band) so the
      // viewer covers the user's real /purchases page. The cursor demo
      // inside the viewer runs against this surface; the cursor itself
      // lives at an even higher z-index already.
      className="fixed inset-0 z-[400] bg-surface-raised flex flex-col"
      role="dialog"
      aria-modal="true"
      aria-label="Demo purchases — Alex's account"
    >
      {/* Demo banner — sticky header that signals "you're looking at a
          demo" so users don't mistake Alex's data for their own. */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-amber-200 dark:border-amber-500/30 bg-amber-50 dark:bg-amber-500/10 flex-shrink-0">
        <div className="flex items-center gap-3">
          <span className="inline-flex items-center gap-2 px-2.5 py-1 text-meta font-medium bg-amber-100 dark:bg-amber-500/20 text-amber-800 dark:text-amber-200 rounded-full">
            <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
            Demo view
          </span>
          <p className="text-body text-amber-900">
            You&apos;re looking at Alex&apos;s account — read-only fake data.
          </p>
        </div>
        <button
          type="button"
          onClick={onClose}
          data-tour-target="demo-purchases-back-button"
          data-testid="demo-purchases-back-button"
          className="ros-btn-raise px-3 py-1.5 text-body bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition-colors"
        >
          Back to my page
        </button>
      </div>

      {/* Scrollable body — the cursor's smooth-scroll glide in
          `purchases-demo-charts` targets this element. */}
      <div
        ref={scrollContainerRef}
        className="flex-1 overflow-auto p-6"
        data-testid="demo-purchases-scroll"
      >
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-heading font-semibold text-foreground">
              Purchases <span className="text-foreground-muted">/ Alex (demo)</span>
            </h2>
            <p className="text-body text-foreground-muted mt-0.5">
              {purchaseTasks.length} purchase order
              {purchaseTasks.length !== 1 ? "s" : ""} · $
              {grandTotal.toFixed(2)} total
            </p>
          </div>
        </div>

        {loading ? (
          <div className="text-center py-16">
            <p className="text-body text-foreground-muted">Loading demo data…</p>
          </div>
        ) : sortedTasks.length === 0 ? (
          <div className="text-center py-16">
            <p className="text-title text-foreground-muted mb-2">
              No demo purchases available
            </p>
            <p className="text-body text-foreground-muted">
              The demo fixtures didn&apos;t include any purchase tasks. The
              spending dashboard below will show zeroed totals.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {sortedTasks.map((task) => {
              const items = purchasesByTask[`${task.owner}:${task.id}`] ?? [];
              const taskTotal = items.reduce(
                (sum, i) => sum + (i.total_price ?? 0),
                0,
              );
              const project = (data?.projects ?? []).find(
                (p) =>
                  p.id === task.project_id && p.owner === task.owner,
              );
              const projectDisplayName =
                project && isMiscProject(project)
                  ? MISC_CATEGORY_LABEL
                  : project?.name ?? "Uncategorized";
              return (
                <div
                  key={`${task.owner}:${task.id}`}
                  className="bg-surface-raised border border-border rounded-xl px-5 py-3"
                  data-testid="demo-purchase-row"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div
                        className={`w-2.5 h-2.5 rounded-full ${
                          task.is_complete ? "bg-green-500" : "bg-foreground-muted/30"
                        }`}
                      />
                      <div>
                        <h3 className="text-body font-semibold text-foreground">
                          {task.name}
                        </h3>
                        <p className="text-meta text-foreground-muted">
                          {projectDisplayName} · {task.start_date} ·{" "}
                          {items.length} item{items.length !== 1 ? "s" : ""}
                        </p>
                      </div>
                    </div>
                    <span className="text-body font-semibold text-foreground">
                      ${taskTotal.toFixed(2)}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* SpendingDashboard — the headline feature of the demo viewer.
            Powered by the same component the real /purchases page uses
            (with no project-filter override since the demo user has no
            global filter state). Carries an anchor so the cursor demo's
            scroll-to-dashboard glide can target it. */}
        {!loading && (
          <div data-tour-target="demo-spending-dashboard">
            <SpendingDashboard
              purchaseItems={data?.purchaseItems ?? []}
              tasks={data?.tasks ?? []}
              projects={data?.projects ?? []}
              fundingAccounts={data?.fundingAccounts ?? []}
              selectedProjectIds={[]}
            />
          </div>
        )}
      </div>
    </div>,
    document.body,
  );
}
