"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { usePathname, useRouter } from "next/navigation";
import BeakerBot from "./BeakerBot";
import OnboardingTipCard, {
  type OnboardingTipCardTutorialControls,
} from "./OnboardingTipCard";
import { ONBOARDING_TIPS, type OnboardingTip } from "@/lib/onboarding/tips";
import { findOnboardingTarget } from "@/lib/onboarding/use-onboarding-target";

/**
 * Phase-4 guided tutorial sequencer. Mounted by `<OnboardingProvider>`
 * when both `isDemoOrWikiCapture()` and `isTutorialMode()` are true,
 * i.e. the user opened `/demo?tutorial=1` in a new tab via the welcome
 * modal's "Walk me through it" button.
 *
 * Walks the user through every tip in `ONBOARDING_TIPS` in priority
 * order (the catalog order). For each tip:
 *
 *   1. Pushes the tip's route, plus any popup-open query param the
 *      tip needs (`openProject` / `openMethod` / `openTask` for tips
 *      whose target lives inside a detail popup). Always preserves
 *      `?tutorial=1` so the sequencer's mount gate stays satisfied
 *      across in-tour navigations.
 *   2. Polls the DOM up to `TARGET_POLL_MS` for the tip's data-attr
 *      target — this covers route mount + popup mount + ref attach.
 *      If the target never appears the sequencer auto-skips so a
 *      flaky DOM doesn't trap the user.
 *   3. Renders `<OnboardingTipCard>` with `tutorial={...}` so the
 *      footer becomes Back / Skip / Next + progress text + an End
 *      link. The X close button asks for confirm (handled inside the
 *      card) before calling `onEnd`.
 *
 * After the last tip (or any End click), renders a small centered
 * end-screen with BeakerBot in the `cheering` pose plus a
 * "Close this tab" button. `window.close()` is best-effort — it only
 * works for tabs JS opened, which is exactly our case (welcome modal
 * uses `window.open`).
 *
 * SSR-safe: the portal block guards on `mounted` after the first
 * client effect.
 */

/** Demo lab IDs the sequencer deep-links to for popup-gated tips.
 *  Sourced from `wiki-capture-fixture.ts` — alex's project/task IDs
 *  and the public methods catalog. The fixture is regenerated by
 *  `scripts/generate-demo-data.mjs` from the on-disk demo lab; if
 *  those IDs ever shift, this map is the only place to update. */
const TUTORIAL_DEMO_IDS = {
  /** alex's project 1 ("Engineer FakeYeast for biofuel") — first
   *  active project. */
  archiveProjectId: 1,
  /** Public method 1 (the demo "Plasmid mini-prep" protocol) — owner
   *  is the `public` namespace, surfaces in alex's methods list as a
   *  shared/public method she can preview. */
  publicMethodId: 1,
  /** alex's task 2 ("Yeast transformation: pYES-GAL1::flbA") — first
   *  experiment-type task with a non-trivial method attachment, so
   *  the task popup has plenty of content to demonstrate fullscreen
   *  on. */
  fullscreenTaskId: 2,
} as const;

/** How long to poll the DOM for a tip's target before auto-skipping.
 *  The ?openProject / ?openMethod / ?openTask deep-link handlers run
 *  inside a useEffect that needs the page's react-query cache to
 *  populate first (~few hundred ms in demo mode), so 3s is generous
 *  but bounded. */
const TARGET_POLL_MS = 3000;
/** Polling interval inside the wait window. */
const TARGET_POLL_INTERVAL_MS = 100;

/** Per-tip overrides for the tutorial walk: which popup to deep-link
 *  open, and any per-tip pacing tweaks. Keyed by tip id. Not in
 *  `tips.ts` because this is a tour-only concern — the catalog stays
 *  pure. */
interface TutorialStepConfig {
  /** Build the URL the sequencer should `router.push` for this tip.
   *  Always preserves `?tutorial=1`. */
  url: string;
  /** Optional pacing delay (ms) AFTER navigation completes and BEFORE
   *  we start polling for the target. Used by `gantt-animations` so
   *  the burst-on-show animation doesn't kick off mid-route-change. */
  preTargetDelayMs?: number;
}

function buildStepConfig(tip: OnboardingTip): TutorialStepConfig {
  const tutorialQuery = "tutorial=1";
  switch (tip.id) {
    case "archive-projects":
      return {
        url: `/?openProject=${TUTORIAL_DEMO_IDS.archiveProjectId}&${tutorialQuery}`,
      };
    case "public-methods":
      return {
        url: `/methods?openMethod=${TUTORIAL_DEMO_IDS.publicMethodId}&${tutorialQuery}`,
      };
    case "fullscreen-task":
      return {
        url: `/?openTask=${TUTORIAL_DEMO_IDS.fullscreenTaskId}&${tutorialQuery}`,
      };
    case "gantt-animations":
      // Give the route a beat to settle before the animation-burst
      // hook fires inside `<OnboardingTipCard>`. Keeps the burst from
      // overlapping the route-transition shimmer.
      return { url: `/gantt?${tutorialQuery}`, preTargetDelayMs: 350 };
    default:
      // Plain route — no popup, no extra params.
      return { url: `${tip.route}?${tutorialQuery}` };
  }
}

export default function OnboardingTutorialSequencer() {
  const router = useRouter();
  const pathname = usePathname();

  /** 0-based index into `ONBOARDING_TIPS`. `null` once the tour ends
   *  so the end-screen takes over. */
  const [currentIndex, setCurrentIndex] = useState<number>(0);
  /** True once the user has hit End or walked past the last tip. */
  const [tourComplete, setTourComplete] = useState(false);
  /** Resolved DOM target for the current tip — null while we poll. */
  const [target, setTarget] = useState<HTMLElement | null>(null);
  /** Portal-mount flag (createPortal needs document.body). */
  const [mounted, setMounted] = useState(false);

  /** Track in-flight polling so an early Next click cancels the
   *  previous step's poll loop. */
  const pollHandleRef = useRef<number | null>(null);
  const pollDeadlineRef = useRef<number>(0);

  useEffect(() => {
    setMounted(true);
  }, []);

  const currentTip: OnboardingTip | null =
    !tourComplete && currentIndex < ONBOARDING_TIPS.length
      ? ONBOARDING_TIPS[currentIndex]
      : null;

  const cancelPoll = useCallback(() => {
    if (pollHandleRef.current !== null) {
      window.clearTimeout(pollHandleRef.current);
      pollHandleRef.current = null;
    }
  }, []);

  // ── Per-step navigation + target-poll loop ───────────────────────
  // Runs whenever the active tip changes. Cancels any prior poll, kicks
  // off router.push for the new tip's URL, then polls the DOM for the
  // target. If we already happen to be on the right route AND the
  // target is in the DOM (e.g. the very first tip lands on / and home
  // already mounted), we short-circuit the navigate and set target
  // immediately so there's no flash.
  useEffect(() => {
    cancelPoll();
    setTarget(null);
    if (!currentTip) return;

    const config = buildStepConfig(currentTip);
    // Compare just the pathname since `pathname` doesn't include the
    // query string. We always navigate when the route differs OR when
    // a popup-open param is needed — we can't tell from the pathname
    // alone whether the popup is open, so the route-match short-circuit
    // only fires for plain-route tips.
    const targetPath = config.url.split("?")[0];
    const needsDeepLink =
      currentTip.id === "archive-projects" ||
      currentTip.id === "public-methods" ||
      currentTip.id === "fullscreen-task";
    const skipNavigation = pathname === targetPath && !needsDeepLink;
    if (!skipNavigation) {
      router.push(config.url);
    }

    pollDeadlineRef.current = Date.now() + TARGET_POLL_MS;
    const startDelay = config.preTargetDelayMs ?? 0;

    const tryFind = () => {
      pollHandleRef.current = null;
      const el = findOnboardingTarget(currentTip.target);
      if (el) {
        setTarget(el);
        return;
      }
      if (Date.now() >= pollDeadlineRef.current) {
        // Best-effort: target never appeared. Stay on this step with
        // `target = null` so the user sees the card without a glow
        // anchor — they can still click Next/Skip to move on. This
        // is preferable to silently auto-skipping since the user gets
        // a clear "huh, nothing's highlighted, let me Skip" signal.
        // eslint-disable-next-line no-console
        console.warn(
          `[onboarding-tutorial] Target "${currentTip.target}" not found within ${TARGET_POLL_MS}ms; rendering card without anchor.`,
        );
        return;
      }
      pollHandleRef.current = window.setTimeout(
        tryFind,
        TARGET_POLL_INTERVAL_MS,
      );
    };

    pollHandleRef.current = window.setTimeout(
      tryFind,
      Math.max(TARGET_POLL_INTERVAL_MS, startDelay),
    );

    return () => {
      cancelPoll();
    };
    // pathname is in the deps so a real route change re-runs the
    // effect; without it, the very-first-mount case where `pathname`
    // becomes available a tick after mount would never re-evaluate
    // skipNavigation.
  }, [currentTip, pathname, router, cancelPoll]);

  // ── Tutorial control handlers ─────────────────────────────────────
  const handleBack = useCallback(() => {
    setCurrentIndex((i) => Math.max(0, i - 1));
  }, []);

  const handleNext = useCallback(() => {
    setCurrentIndex((i) => {
      const next = i + 1;
      if (next >= ONBOARDING_TIPS.length) {
        // Past the last tip — flip to end-screen.
        setTourComplete(true);
        return i;
      }
      return next;
    });
  }, []);

  const handleSkip = useCallback(() => {
    handleNext();
  }, [handleNext]);

  const handleEnd = useCallback(() => {
    cancelPoll();
    setTourComplete(true);
  }, [cancelPoll]);

  const handleCloseTab = useCallback(() => {
    // Best-effort: only works for tabs that JS opened (the welcome
    // modal uses window.open). On a manually-pasted /demo?tutorial=1
    // URL this is a no-op — the button just sits there, which is
    // acceptable per the spec.
    if (typeof window !== "undefined") {
      window.close();
    }
  }, []);

  // OnboardingTipCard's onClose prop is required even though the
  // tutorial footer doesn't call its outcome surface. Wire it to
  // `handleEnd` as a defensive fallback so any future code path that
  // bypasses the tutorial footer (e.g. an Esc handler) still ends
  // the tour cleanly.
  const handleCardClose = useCallback(() => {
    handleEnd();
  }, [handleEnd]);

  if (!mounted) return null;

  // ── End-screen ────────────────────────────────────────────────────
  if (tourComplete) {
    return createPortal(
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="onboarding-tutorial-end-title"
        className="fixed inset-0 z-[300] flex items-center justify-center bg-black/30 backdrop-blur-sm"
      >
        <div className="bg-white rounded-2xl shadow-2xl border border-gray-200 max-w-md w-[420px] mx-4 overflow-hidden">
          <div className="p-7 flex items-start gap-5">
            <div
              aria-hidden
              className="flex-shrink-0"
              style={{ width: 96, height: 96 }}
            >
              <BeakerBot
                pose="cheering"
                direction="right"
                className="w-full h-full text-sky-500"
              />
            </div>
            <div className="flex-1 min-w-0">
              <h2
                id="onboarding-tutorial-end-title"
                className="text-xl font-semibold text-gray-900"
              >
                You&apos;re all caught up!
              </h2>
              <p className="mt-2 text-sm text-gray-700 leading-relaxed">
                Close this tab to head back to your work — your real
                folder&apos;s still waiting.
              </p>
              <div className="mt-5">
                <button
                  type="button"
                  onClick={handleCloseTab}
                  className="w-full px-4 py-2.5 text-base font-medium bg-sky-500 hover:bg-sky-600 text-white rounded-lg transition-colors shadow-sm"
                >
                  Close this tab
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>,
      document.body,
    );
  }

  // ── Per-tip card ──────────────────────────────────────────────────
  if (!currentTip) return null;

  const tutorialControls: OnboardingTipCardTutorialControls = {
    currentIndex,
    totalCount: ONBOARDING_TIPS.length,
    onBack: handleBack,
    onSkip: handleSkip,
    onNext: handleNext,
    onEnd: handleEnd,
  };

  return (
    <OnboardingTipCard
      key={currentTip.id}
      tip={currentTip}
      target={target}
      tutorial={tutorialControls}
      onClose={handleCardClose}
    />
  );
}
