"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { usePathname, useRouter } from "next/navigation";
import BeakerBot from "./BeakerBot";
import OnboardingTipCard, {
  type OnboardingTipCardTutorialControls,
} from "./OnboardingTipCard";
import { ONBOARDING_TIPS, type OnboardingTip } from "@/lib/onboarding/tips";
import { findOnboardingTarget } from "@/lib/onboarding/use-onboarding-target";
import {
  broadcastTutorialSignal,
  subscribeTutorialSignal,
} from "@/lib/telegram/tutorial-signal";
import {
  getTutorialMode,
  type TutorialMode,
} from "@/lib/file-system/wiki-capture-mock";

/**
 * Phase-4 guided tutorial sequencer. Mounted by `<OnboardingProvider>`
 * when both `isDemoOrWikiCapture()` and `getTutorialMode()` is
 * non-null, i.e. the user opened `/demo?tutorial=1` or
 * `/demo?tutorial=telegram` in a new tab.
 *
 * Two modes, parameterized by `getTutorialMode()`:
 *
 *   - `"full"` (`?tutorial=1`) — the original 10-tip intro tour,
 *     opened from the welcome modal's "Walk me through it" button.
 *     Walks the full catalog in priority order.
 *   - `"telegram"` (`?tutorial=telegram`) — standalone Telegram-setup
 *     walkthrough: only the `telegram-send-to-task` catalog tip + the
 *     first-photo interstitial + the confirmation card + the
 *     end-screen. Entry points: the "Set up Telegram" button on
 *     `/settings#telegram` and the "Force Telegram walkthrough" entry
 *     in the dev tip-force dropdown.
 *
 * For each catalog tip in either mode:
 *
 *   1. Pushes the tip's route, plus any popup-open query param the
 *      tip needs (`openProject` / `openMethod` / `openTask` for tips
 *      whose target lives inside a detail popup). Always preserves
 *      `?tutorial=1` so the sequencer's mount gate stays satisfied
 *      across in-tour navigations.
 *   2. Polls the DOM up to `TARGET_POLL_MS` for the tip's data-attr
 *      target, this covers route mount + popup mount + ref attach.
 *      If the target never appears the sequencer auto-skips so a
 *      flaky DOM doesn't trap the user.
 *   3. Renders `<OnboardingTipCard>` with `tutorial={...}` so the
 *      footer becomes Back / Skip / Next + progress text + an End
 *      link. The X close button asks for confirm (handled inside the
 *      card) before calling `onEnd`.
 *
 * Plus one virtual interstitial: the **first-photo step**, fired
 * immediately AFTER the `telegram-send-to-task` catalog tip. The card
 * asks the user to text a photo from their phone; the sequencer
 * subscribes to the cross-tab `photo-arrived` broadcast (sent from
 * the user's REAL ResearchOS tab when its polling loop processes a
 * Telegram photo) and advances to a confirmation card on receipt.
 *
 * On mount of the first-photo step, the sequencer broadcasts
 * `tutorial-state: first-photo` so the polling tab's orchestrator can
 * write the user's `_telegram_tutorial.json` sidecar (the demo tab's
 * mock fileService can't write the real sidecar itself). On advance /
 * skip / End, it broadcasts `tutorial-state: null` to clear.
 *
 * After the last tip (or any End click), renders a small centered
 * end-screen with BeakerBot in the `cheering` pose plus a
 * "Close this tab" button. `window.close()` is best-effort, it only
 * works for tabs JS opened, which is exactly our case (welcome modal
 * uses `window.open`).
 *
 * SSR-safe: the portal block guards on `mounted` after the first
 * client effect.
 */

/** Demo lab IDs the sequencer deep-links to for popup-gated tips.
 *  Sourced from `wiki-capture-fixture.ts`, alex's project/task IDs
 *  and the public methods catalog. The fixture is regenerated by
 *  `scripts/generate-demo-data.mjs` from the on-disk demo lab; if
 *  those IDs ever shift, this map is the only place to update. */
const TUTORIAL_DEMO_IDS = {
  /** alex's project 1 ("Engineer FakeYeast for biofuel"), first
   *  active project. */
  archiveProjectId: 1,
  /** Public method 1 (the demo "Plasmid mini-prep" protocol), owner
   *  is the `public` namespace, surfaces in alex's methods list as a
   *  shared/public method she can preview. */
  publicMethodId: 1,
  /** alex's task 2 ("Yeast transformation: pYES-GAL1::flbA"), first
   *  experiment-type task with a non-trivial method attachment, so
   *  the task popup has plenty of content to demonstrate fullscreen
   *  on. */
  fullscreenTaskId: 2,
} as const;

/** How long to poll the DOM for a tip's target before auto-skipping.
 *  The ?openProject / ?openMethod / ?openTask deep-link handlers run
 *  inside a useEffect that needs the page's react-query cache to
 *  populate first (~few hundred ms in demo mode), so 3s is generous
 *  but bounded. */
const TARGET_POLL_MS = 3000;
/** Polling interval inside the wait window. */
const TARGET_POLL_INTERVAL_MS = 100;

/** Per-tip overrides for the tutorial walk: which popup to deep-link
 *  open, and any per-tip pacing tweaks. Keyed by tip id. Not in
 *  `tips.ts` because this is a tour-only concern, the catalog stays
 *  pure. */
interface TutorialStepConfig {
  /** Build the URL the sequencer should `router.push` for this tip.
   *  Always preserves `?tutorial=1`. */
  url: string;
  /** Optional pacing delay (ms) AFTER navigation completes and BEFORE
   *  we start polling for the target. Used by `gantt-animations` so
   *  the burst-on-show animation doesn't kick off mid-route-change. */
  preTargetDelayMs?: number;
}

function buildStepConfig(
  tip: OnboardingTip,
  mode: TutorialMode,
): TutorialStepConfig {
  // Preserve the active mode across in-tour navigations so a re-mount
  // (browser back/forward, hard refresh) lands the sequencer in the
  // same flow it started in.
  const tutorialQuery = mode === "telegram" ? "tutorial=telegram" : "tutorial=1";
  switch (tip.id) {
    case "archive-projects":
      return {
        url: `/?openProject=${TUTORIAL_DEMO_IDS.archiveProjectId}&${tutorialQuery}`,
      };
    case "public-methods":
      return {
        url: `/methods?openMethod=${TUTORIAL_DEMO_IDS.publicMethodId}&${tutorialQuery}`,
      };
    case "fullscreen-task":
      return {
        url: `/?openTask=${TUTORIAL_DEMO_IDS.fullscreenTaskId}&${tutorialQuery}`,
      };
    case "gantt-animations":
      // Give the route a beat to settle before the animation-burst
      // hook fires inside `<OnboardingTipCard>`. Keeps the burst from
      // overlapping the route-transition shimmer.
      return { url: `/gantt?${tutorialQuery}`, preTargetDelayMs: 350 };
    default:
      // Plain route, no popup, no extra params.
      return { url: `${tip.route}?${tutorialQuery}` };
  }
}

/** Index in `ONBOARDING_TIPS` of the Telegram tip. The first-photo
 *  interstitial fires immediately after this tip. Computed once at
 *  module load; the catalog ordering is stable. */
const TELEGRAM_TIP_INDEX = ONBOARDING_TIPS.findIndex(
  (t) => t.id === "telegram-send-to-task",
);

/** First-photo interstitial timeout: how long we'll wait for the
 *  cross-tab `photo-arrived` signal before showing the timeout
 *  fallback copy. 90s per the spec, bounded so a stale step doesn't
 *  trap the user behind a non-functional polling tab. Skip / End stay
 *  available throughout. */
const FIRST_PHOTO_TIMEOUT_MS = 90_000;

/** Sequencer phase. Catalog tips drive `currentIndex`; the
 *  first-photo step has its own three-state lifecycle when it's the
 *  active phase. */
type SequencerPhase =
  | { kind: "catalog"; index: number }
  | { kind: "first-photo-waiting" }
  | { kind: "first-photo-timeout" }
  | { kind: "first-photo-confirmed" }
  | { kind: "complete" };

export default function OnboardingTutorialSequencer() {
  const router = useRouter();
  const pathname = usePathname();

  /** Read once on mount. `getTutorialMode()` reads from the URL; we
   *  snapshot it here so a mid-tour URL mutation can't yank the
   *  sequencer between modes. Default to `"full"` if the mount gate
   *  let us through with no mode value — defensive; the gate
   *  shouldn't allow that. */
  const [mode] = useState<TutorialMode>(() => getTutorialMode() ?? "full");

  /** Single source of truth for "where are we in the tour". The
   *  `index` shape encodes catalog progress; the other shapes encode
   *  the first-photo virtual step. In `"telegram"` mode, `index`
   *  always equals `TELEGRAM_TIP_INDEX` — the only catalog step in
   *  that flow. */
  const [phase, setPhase] = useState<SequencerPhase>(() => ({
    kind: "catalog",
    index: mode === "telegram" ? TELEGRAM_TIP_INDEX : 0,
  }));
  /** Resolved DOM target for the current tip, null while we poll. */
  const [target, setTarget] = useState<HTMLElement | null>(null);
  /** Portal-mount flag (createPortal needs document.body). */
  const [mounted, setMounted] = useState(false);

  /** Track in-flight polling so an early Next click cancels the
   *  previous step's poll loop. */
  const pollHandleRef = useRef<number | null>(null);
  const pollDeadlineRef = useRef<number>(0);
  /** Timeout handle for the first-photo "waiting too long" fallback.
   *  Cleared whenever the phase changes off the waiting state. */
  const firstPhotoTimeoutRef = useRef<number | null>(null);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- SSR-hydration gate: the component renders null until mounted so the server-rendered tree matches first client paint, then flips to mounted=true to begin the tutorial. Cannot be useMemo (mounted is a side-effect signal, not derived state); cannot be a lazy useState initializer (would be true on the SSR pass and re-introduce the hydration mismatch this guard exists to prevent).
    setMounted(true);
  }, []);

  const currentTip: OnboardingTip | null =
    phase.kind === "catalog" && phase.index < ONBOARDING_TIPS.length
      ? ONBOARDING_TIPS[phase.index]
      : null;

  const cancelPoll = useCallback(() => {
    if (pollHandleRef.current !== null) {
      window.clearTimeout(pollHandleRef.current);
      pollHandleRef.current = null;
    }
  }, []);

  const cancelFirstPhotoTimeout = useCallback(() => {
    if (firstPhotoTimeoutRef.current !== null) {
      window.clearTimeout(firstPhotoTimeoutRef.current);
      firstPhotoTimeoutRef.current = null;
    }
  }, []);

  // ── Per-step navigation + target-poll loop ───────────────────────
  // Runs whenever the active tip changes. Cancels any prior poll, kicks
  // off router.push for the new tip's URL, then polls the DOM for the
  // target. If we already happen to be on the right route AND the
  // target is in the DOM (e.g. the very first tip lands on / and home
  // already mounted), we short-circuit the navigate and set target
  // immediately so there's no flash.
  useEffect(() => {
    cancelPoll();
    // eslint-disable-next-line react-hooks/set-state-in-effect -- per-step lifecycle: must clear the prior step's target before async DOM-polling for the new tip resolves, otherwise the glow anchor flickers on the old element while router.push + setTimeout-poll converge. Cannot be useMemo (target is resolved async from DOM, not derived from currentTip); cannot be sync-prop-via-key (the surrounding refs pollHandleRef/pollDeadlineRef/firstPhotoTimeoutRef must persist across step transitions for cross-step cancellation to work, and re-mounting on currentTip change would null them out mid-cancel).
    setTarget(null);
    if (!currentTip) return;

    const config = buildStepConfig(currentTip, mode);
    // Compare just the pathname since `pathname` doesn't include the
    // query string. We always navigate when the route differs OR when
    // a popup-open param is needed, we can't tell from the pathname
    // alone whether the popup is open, so the route-match short-circuit
    // only fires for plain-route tips.
    const targetPath = config.url.split("?")[0];
    const needsDeepLink =
      currentTip.id === "archive-projects" ||
      currentTip.id === "public-methods" ||
      currentTip.id === "fullscreen-task";
    const skipNavigation = pathname === targetPath && !needsDeepLink;
    if (!skipNavigation) {
      router.push(config.url);
    }

    pollDeadlineRef.current = Date.now() + TARGET_POLL_MS;
    const startDelay = config.preTargetDelayMs ?? 0;

    const tryFind = () => {
      pollHandleRef.current = null;
      const el = findOnboardingTarget(currentTip.target);
      if (el) {
        setTarget(el);
        return;
      }
      if (Date.now() >= pollDeadlineRef.current) {
        // Best-effort: target never appeared. Stay on this step with
        // `target = null` so the user sees the card without a glow
        // anchor, they can still click Next/Skip to move on. This
        // is preferable to silently auto-skipping since the user gets
        // a clear "huh, nothing's highlighted, let me Skip" signal.
        // eslint-disable-next-line no-console
        console.warn(
          `[onboarding-tutorial] Target "${currentTip.target}" not found within ${TARGET_POLL_MS}ms; rendering card without anchor.`,
        );
        return;
      }
      pollHandleRef.current = window.setTimeout(
        tryFind,
        TARGET_POLL_INTERVAL_MS,
      );
    };

    pollHandleRef.current = window.setTimeout(
      tryFind,
      Math.max(TARGET_POLL_INTERVAL_MS, startDelay),
    );

    return () => {
      cancelPoll();
    };
    // pathname is in the deps so a real route change re-runs the
    // effect; without it, the very-first-mount case where `pathname`
    // becomes available a tick after mount would never re-evaluate
    // skipNavigation. `mode` is included because `buildStepConfig`
    // reads it for the preserved query string.
  }, [currentTip, pathname, router, cancelPoll, mode]);

  // ── First-photo step lifecycle: signal the polling tab + listen ──
  // On mount of the waiting phase, broadcast the "first-photo" state
  // so the polling tab's orchestrator writes the sidecar. Subscribe
  // to `photo-arrived` to advance. Start a 90s timeout for the
  // "polling tab not listening" fallback. All of this gets cleaned up
  // on unmount or phase change.
  useEffect(() => {
    if (phase.kind !== "first-photo-waiting") return;

    broadcastTutorialSignal({ type: "tutorial-state", step: "first-photo" });

    const unsubscribe = subscribeTutorialSignal((signal) => {
      if (signal.type !== "photo-arrived") return;
      cancelFirstPhotoTimeout();
      setPhase({ kind: "first-photo-confirmed" });
    });

    cancelFirstPhotoTimeout();
    firstPhotoTimeoutRef.current = window.setTimeout(() => {
      firstPhotoTimeoutRef.current = null;
      setPhase((cur) =>
        cur.kind === "first-photo-waiting"
          ? { kind: "first-photo-timeout" }
          : cur,
      );
    }, FIRST_PHOTO_TIMEOUT_MS);

    return () => {
      unsubscribe();
      cancelFirstPhotoTimeout();
    };
  }, [phase.kind, cancelFirstPhotoTimeout]);

  // Clear the polling-tab sidecar whenever we leave any first-photo
  // phase (advance / skip / End / unmount). Idempotent on the receiving
  // end so a duplicate clear is harmless.
  useEffect(() => {
    const inFirstPhotoPhase =
      phase.kind === "first-photo-waiting" ||
      phase.kind === "first-photo-timeout" ||
      phase.kind === "first-photo-confirmed";
    if (inFirstPhotoPhase) return;
    broadcastTutorialSignal({ type: "tutorial-state", step: null });
  }, [phase.kind]);

  // Make sure unmount clears the sidecar too (the above effect doesn't
  // run on unmount because the deps haven't changed). Belt-and-braces.
  useEffect(() => {
    return () => {
      broadcastTutorialSignal({ type: "tutorial-state", step: null });
    };
  }, []);

  // ── Tutorial control handlers ─────────────────────────────────────
  /** Move the catalog index forward by one, OR transition into the
   *  first-photo interstitial after the Telegram tip. Used by both
   *  Next and Skip on catalog tips. */
  const advanceFromCatalog = useCallback(() => {
    setPhase((cur) => {
      if (cur.kind !== "catalog") return cur;
      // Special transition: after the Telegram tip, fire the
      // first-photo interstitial before advancing the index. Same in
      // both modes — the interstitial is part of the Telegram step.
      if (cur.index === TELEGRAM_TIP_INDEX) {
        return { kind: "first-photo-waiting" };
      }
      const next = cur.index + 1;
      if (next >= ONBOARDING_TIPS.length) {
        return { kind: "complete" };
      }
      return { kind: "catalog", index: next };
    });
  }, []);

  /** Move past any first-photo phase. In `"full"` mode this advances
   *  to the catalog tip after the Telegram tip; in `"telegram"` mode
   *  the Telegram step is the only step, so we land on the end-screen
   *  directly. */
  const advancePastFirstPhoto = useCallback(() => {
    setPhase(() => {
      if (mode === "telegram") {
        return { kind: "complete" };
      }
      const next = TELEGRAM_TIP_INDEX + 1;
      if (next >= ONBOARDING_TIPS.length) {
        return { kind: "complete" };
      }
      return { kind: "catalog", index: next };
    });
  }, [mode]);

  const handleBack = useCallback(() => {
    setPhase((cur) => {
      // Back inside any first-photo phase returns to the Telegram tip.
      if (
        cur.kind === "first-photo-waiting" ||
        cur.kind === "first-photo-timeout" ||
        cur.kind === "first-photo-confirmed"
      ) {
        return { kind: "catalog", index: TELEGRAM_TIP_INDEX };
      }
      if (cur.kind !== "catalog") return cur;
      return { kind: "catalog", index: Math.max(0, cur.index - 1) };
    });
  }, []);

  const handleNext = useCallback(() => {
    if (
      phase.kind === "first-photo-waiting" ||
      phase.kind === "first-photo-timeout" ||
      phase.kind === "first-photo-confirmed"
    ) {
      advancePastFirstPhoto();
      return;
    }
    advanceFromCatalog();
  }, [phase.kind, advanceFromCatalog, advancePastFirstPhoto]);

  const handleSkip = useCallback(() => {
    handleNext();
  }, [handleNext]);

  const handleEnd = useCallback(() => {
    cancelPoll();
    cancelFirstPhotoTimeout();
    setPhase({ kind: "complete" });
  }, [cancelPoll, cancelFirstPhotoTimeout]);

  const handleCloseTab = useCallback(() => {
    // Best-effort: only works for tabs that JS opened (the welcome
    // modal uses window.open). On a manually-pasted /demo?tutorial=1
    // URL this is a no-op, the button just sits there, which is
    // acceptable per the spec.
    if (typeof window !== "undefined") {
      window.close();
    }
  }, []);

  // OnboardingTipCard's onClose prop is required even though the
  // tutorial footer doesn't call its outcome surface. Wire it to
  // `handleEnd` as a defensive fallback so any future code path that
  // bypasses the tutorial footer (e.g. an Esc handler) still ends
  // the tour cleanly.
  const handleCardClose = useCallback(() => {
    handleEnd();
  }, [handleEnd]);

  if (!mounted) return null;

  // ── End-screen ────────────────────────────────────────────────────
  if (phase.kind === "complete") {
    return createPortal(
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="onboarding-tutorial-end-title"
        className="fixed inset-0 z-[300] flex items-center justify-center bg-black/30 backdrop-blur-sm"
      >
        <div className="bg-white rounded-2xl shadow-2xl border border-gray-200 max-w-md w-[420px] mx-4 overflow-hidden">
          <div className="p-7 flex items-start gap-5">
            <div
              aria-hidden
              className="flex-shrink-0"
              style={{ width: 96, height: 96 }}
            >
              <BeakerBot
                pose="cheering"
                direction="right"
                className="w-full h-full text-sky-500"
              />
            </div>
            <div className="flex-1 min-w-0">
              <h2
                id="onboarding-tutorial-end-title"
                className="text-xl font-semibold text-gray-900"
              >
                You&apos;re all caught up!
              </h2>
              <p className="mt-2 text-sm text-gray-700 leading-relaxed">
                Close this tab to head back to your work, your real
                folder&apos;s still waiting.
              </p>
              <div className="mt-5">
                <button
                  type="button"
                  onClick={handleCloseTab}
                  className="w-full px-4 py-2.5 text-base font-medium bg-sky-500 hover:bg-sky-600 text-white rounded-lg transition-colors shadow-sm"
                >
                  Close this tab
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>,
      document.body,
    );
  }

  // ── First-photo interstitial ──────────────────────────────────────
  // A modal-shaped card (similar to the end-screen) that doesn't anchor
  // to any DOM target. Three sub-states with shared chrome:
  //
  //   waiting   — "send a photo from your phone now"
  //   timeout   — same card with a fallback footer hint
  //   confirmed — "got your photo" success card
  //
  // Footer always carries the same Back / Skip / End controls so the
  // user can bail if Telegram isn't paired in their real folder.
  if (
    phase.kind === "first-photo-waiting" ||
    phase.kind === "first-photo-timeout" ||
    phase.kind === "first-photo-confirmed"
  ) {
    const isConfirmed = phase.kind === "first-photo-confirmed";
    const isTimeout = phase.kind === "first-photo-timeout";
    const title = isConfirmed
      ? "Got your photo!"
      : "Now try it for real";
    const body = isConfirmed
      ? "Head back to your real folder to see the photo on the experiment. Switch tabs whenever you're ready, the rest of the tour waits here."
      : "Take your phone out and text a photo to your Telegram bot now. We'll watch for it on this side.";
    const beakerPose: "cheering" | "pointing" = isConfirmed
      ? "cheering"
      : "pointing";

    return createPortal(
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="onboarding-first-photo-title"
        className="fixed inset-0 z-[300] flex items-center justify-center bg-black/30 backdrop-blur-sm"
      >
        <div className="bg-white rounded-2xl shadow-2xl border border-gray-200 max-w-md w-[460px] mx-4 overflow-hidden">
          <div className="p-7 flex items-start gap-5">
            <div
              aria-hidden
              className="flex-shrink-0"
              style={{ width: 96, height: 96 }}
            >
              <BeakerBot
                pose={beakerPose}
                direction="right"
                className="w-full h-full text-sky-500"
              />
            </div>
            <div className="flex-1 min-w-0">
              <h2
                id="onboarding-first-photo-title"
                className="text-xl font-semibold text-gray-900"
              >
                {title}
              </h2>
              <p className="mt-2 text-sm text-gray-700 leading-relaxed">
                {body}
              </p>
              {isTimeout && (
                <p className="mt-3 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 leading-relaxed">
                  If your photo didn&apos;t show up, your real ResearchOS
                  tab might be closed. Skip this step and try again later.
                </p>
              )}
              {!isConfirmed && !isTimeout && (
                <p className="mt-3 text-xs text-gray-500">
                  Not paired yet? Skip this step, you can pair Telegram
                  later from the header pill in your real folder.
                </p>
              )}

              {/* Footer mirrors the catalog-tip tutorial controls so
                  the user has a consistent escape hatch. Back returns
                  to the Telegram tip; Skip / Next moves past the
                  step; End ends the tour outright. */}
              <div className="mt-5 flex items-center justify-between text-xs text-gray-500">
                <span>
                  {mode === "telegram"
                    ? "Send your first photo"
                    : `${TELEGRAM_TIP_INDEX + 1} of ${ONBOARDING_TIPS.length} (send your first photo)`}
                </span>
                <button
                  type="button"
                  onClick={handleEnd}
                  className="text-gray-400 hover:text-gray-700"
                >
                  End tutorial
                </button>
              </div>
              <div className="mt-2 flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleBack}
                    className="px-3 py-2 text-sm font-medium border border-gray-300 text-gray-700 hover:bg-gray-50 rounded-lg transition-colors"
                  >
                    ← Back
                  </button>
                  <button
                    type="button"
                    onClick={handleSkip}
                    className="px-3 py-2 text-sm font-medium text-gray-500 hover:text-gray-700 rounded-lg transition-colors"
                  >
                    Skip
                  </button>
                </div>
                <button
                  type="button"
                  onClick={handleNext}
                  className="px-3 py-2 text-sm font-medium bg-sky-500 hover:bg-sky-600 text-white rounded-lg shadow-sm transition-colors"
                >
                  Next →
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>,
      document.body,
    );
  }

  // ── Per-tip card ──────────────────────────────────────────────────
  if (!currentTip) return null;

  // In telegram mode the only catalog step IS the Telegram tip, so
  // we render it as "1 of 1" rather than its position in the full
  // catalog (which would be a confusing "1 of 10" for a 1-step flow).
  const tutorialControls: OnboardingTipCardTutorialControls = {
    currentIndex: mode === "telegram" ? 0 : phase.kind === "catalog" ? phase.index : 0,
    totalCount: mode === "telegram" ? 1 : ONBOARDING_TIPS.length,
    onBack: handleBack,
    onSkip: handleSkip,
    onNext: handleNext,
    onEnd: handleEnd,
  };

  return (
    <OnboardingTipCard
      key={currentTip.id}
      tip={currentTip}
      target={target}
      tutorial={tutorialControls}
      onClose={handleCardClose}
    />
  );
}
