"use client";

/**
 * "Built on open source" page body (rendered at /open-source).
 *
 * Opens with a sincere thank-you to the open-source and scientific community,
 * then credits the projects ResearchOS is built on: curated highlights grouped
 * by area, the source we vendor directly (SeqViz, TeselaGen tg-oss, the
 * Biopython Tm port), the scientific references behind the calculators, and
 * the full auto-generated dependency list in a collapsible block.
 *
 * All of the factual data (versions, licenses, repo links) comes from
 * public/open-source/credits.json, generated by
 * scripts/build-open-source-credits.mjs off the installed dependency tree, so
 * nothing here is hand-maintained or guessable.
 *
 * Voice rules: warm and concept-first. No em-dashes, no emojis. Every icon is
 * an inline SVG. Icon-only affordances use the shared <Tooltip>, never a
 * native title=.
 */

import { useEffect, useState } from "react";
import Link from "next/link";

import MarketingFooter from "@/components/MarketingFooter";
import MarketingNav from "@/components/MarketingNav";
import Kicker from "@/components/marketing/Kicker";

/* ───────────── data shape (mirrors credits.json) ───────────────────────── */

interface CreditDep {
  name: string;
  version: string;
  license: string;
  repo: string | null;
}

interface HighlightItem extends CreditDep {
  note: string;
}

interface HighlightGroup {
  id: string;
  title: string;
  blurb: string;
  items: HighlightItem[];
}

interface VendoredEntry {
  name: string;
  by: string;
  license: string;
  copyright: string;
  url: string;
  note: string;
}

interface ScientificReference {
  citation: string;
  use: string;
}

interface Credits {
  generatedAt: string;
  appVersion: string;
  dependencyCount: number;
  licenseCounts: Record<string, number>;
  highlightGroups: HighlightGroup[];
  vendored: VendoredEntry[];
  scientificReferences: ScientificReference[];
  dependencies: CreditDep[];
}

/* ───────────── small presentational helpers ────────────────────────────── */

/** External-link arrow, inline SVG (no icon library). */
function ExternalIcon() {
  return (
    <svg
      className="ml-0.5 inline-block h-3 w-3 align-[-1px]"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M7 17 17 7M9 7h8v8" />
    </svg>
  );
}

/** A subtle license pill. */
function LicensePill({ license }: { license: string }) {
  return (
    <span className="inline-flex items-center rounded-full bg-surface-sunken px-2 py-0.5 text-meta font-medium text-foreground-muted">
      {license}
    </span>
  );
}

function PackageLink({ name, repo }: { name: string; repo: string | null }) {
  if (!repo) return <span className="font-mono text-body text-foreground">{name}</span>;
  return (
    <a
      href={repo}
      target="_blank"
      rel="noopener noreferrer"
      className="font-mono text-body text-sky-700 dark:text-sky-300 underline-offset-2 hover:text-sky-900 hover:underline"
    >
      {name}
      <ExternalIcon />
    </a>
  );
}

/* ───────────── page ─────────────────────────────────────────────────────── */

export default function OpenSourceCredits() {
  const [credits, setCredits] = useState<Credits | null>(null);
  const [error, setError] = useState(false);
  const [showAll, setShowAll] = useState(false);

  useEffect(() => {
    let cancelled = false;
    fetch("/open-source/credits.json")
      .then((r) => {
        if (!r.ok) throw new Error(String(r.status));
        return r.json();
      })
      .then((data: Credits) => {
        if (!cancelled) setCredits(data);
      })
      .catch(() => {
        if (!cancelled) setError(true);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="flex min-h-screen flex-col bg-surface-sunken text-foreground">
      <div aria-hidden className="brand-rainbow-bg h-2 w-full" />
      <MarketingNav />

      <main className="mx-auto w-full max-w-4xl flex-1 px-6 py-12">
        {/* ── Heartfelt intro ── */}
        <section className="mb-14">
          <div className="mb-4">
            <Kicker>Thank you</Kicker>
          </div>
          <h1 className="mb-6 text-display font-bold tracking-tight text-foreground sm:text-4xl">
            Built on open source
          </h1>
          <div className="space-y-4 text-title leading-relaxed text-foreground">
            <p>
              ResearchOS exists because thousands of people gave their work
              away. Every screen here rests on open-source software written and
              maintained by volunteers, students, and engineers who chose to
              share. We are deeply grateful to all of them.
            </p>
            <p>
              We are just as grateful to the scientists whose published methods
              we lean on. The calculators reproduce decades of careful
              measurement, freely written down so the rest of us can stand on
              it. That spirit, sharing your work so the next person gets
              further, is the same spirit ResearchOS is built in. It is free
              and open source for exactly that reason.
            </p>
            <p>
              This page is our way of saying so out loud, and of keeping faith
              with the licenses that make all of it possible. Below is the full
              account of what we build on.
            </p>
          </div>
          <p className="mt-5 text-body text-foreground-muted">
            For the people who fund the project directly, see{" "}
            <Link
              href="/thanks"
              className="font-medium text-sky-700 underline-offset-2 hover:underline dark:text-sky-300"
            >
              Sponsors and thanks
            </Link>
            .
          </p>
        </section>

        {error && (
          <p className="rounded-lg border border-amber-200 dark:border-amber-500/30 bg-amber-50 dark:bg-amber-500/15 px-4 py-3 text-body text-amber-800 dark:text-amber-300">
            The credits data could not be loaded right now. The full list also
            lives in THIRD_PARTY_NOTICES and ACKNOWLEDGEMENTS.md in the source
            repository.
          </p>
        )}

        {credits && (
          <>
            {/* ── Newest attribution, featured ── */}
            <section className="mb-14">
              <h2 className="mb-2 text-heading font-semibold text-foreground">
                Recently added
              </h2>
              <p className="mb-5 text-body text-foreground-muted">
                Two pieces of work we want to call out by name.
              </p>
              <div className="grid gap-4 sm:grid-cols-2">
                <FeaturedCard
                  title="expr-eval-fork"
                  license="MIT"
                  href="https://github.com/jorenbroekema/expr-eval"
                  body="The lightweight expression engine behind the scientific calculator tab. It turns a typed formula into a real evaluated result, complete with functions, constants, and angle modes."
                />
                <FeaturedCard
                  title="Biopython Tm port"
                  license="BSD"
                  href="https://github.com/biopython/biopython"
                  body="Our nearest-neighbor primer melting temperature is a faithful TypeScript port of Biopython's MeltingTemp.Tm_NN, with the parameters transcribed verbatim from the source literature."
                />
              </div>
            </section>

            {/* ── Curated highlights by area ── */}
            <section className="mb-14">
              <h2 className="mb-2 text-heading font-semibold text-foreground">
                What powers each part of the app
              </h2>
              <p className="mb-6 text-body text-foreground-muted">
                A few of the projects we rely on most, grouped by where you
                meet them.
              </p>
              <div className="space-y-8">
                {credits.highlightGroups.map((group) => (
                  <div key={group.id}>
                    <h3 className="text-title font-semibold text-foreground">
                      {group.title}
                    </h3>
                    <p className="mb-3 text-body text-foreground-muted">{group.blurb}</p>
                    <ul className="divide-y divide-border overflow-hidden rounded-xl border border-border bg-surface-raised">
                      {group.items.map((item) => (
                        <li
                          key={item.name}
                          className="flex flex-col gap-1 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"
                        >
                          <div className="min-w-0">
                            <PackageLink name={item.name} repo={item.repo} />
                            <p className="mt-0.5 text-body text-foreground-muted">
                              {item.note}
                            </p>
                          </div>
                          <div className="flex flex-shrink-0 items-center gap-2 sm:ml-4">
                            <span className="font-mono text-meta text-foreground-muted">
                              {item.version}
                            </span>
                            <LicensePill license={item.license} />
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </section>

            {/* ── Code we recycle (vendored / ported) ── */}
            <section className="mb-14">
              <h2 className="mb-2 text-heading font-semibold text-foreground">
                Code we recycle
              </h2>
              <p className="mb-6 text-body text-foreground-muted">
                Some projects we do not just depend on, we carry their source
                directly. We keep their licenses and copyright alongside the
                code, exactly as their authors intended.
              </p>
              <div className="space-y-4">
                {credits.vendored.map((v) => (
                  <div
                    key={v.name}
                    className="rounded-xl border border-border bg-surface-raised p-5"
                  >
                    <div className="mb-1 flex flex-wrap items-center gap-2">
                      <a
                        href={v.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-title font-semibold text-sky-700 dark:text-sky-300 underline-offset-2 hover:text-sky-900 hover:underline"
                      >
                        {v.name}
                        <ExternalIcon />
                      </a>
                      <LicensePill license={v.license} />
                    </div>
                    <p className="text-body text-foreground-muted">{v.note}</p>
                    <p className="mt-2 text-meta text-foreground-muted">
                      {v.by}. {v.copyright}
                    </p>
                  </div>
                ))}
              </div>
            </section>

            {/* ── Scientific references ── */}
            <section className="mb-14">
              <h2 className="mb-2 text-heading font-semibold text-foreground">
                Scientific references
              </h2>
              <p className="mb-6 text-body text-foreground-muted">
                The calculators reproduce published methods. The parameters and
                equations come straight from these papers.
              </p>
              <ul className="space-y-4">
                {credits.scientificReferences.map((r) => (
                  <li
                    key={r.citation}
                    className="rounded-xl border border-border bg-surface-raised p-5"
                  >
                    <p className="text-body text-foreground">{r.citation}</p>
                    <p className="mt-1 text-meta text-foreground-muted">{r.use}</p>
                  </li>
                ))}
              </ul>
            </section>

            {/* ── Full dependency list (collapsible) ── */}
            <section className="mb-6">
              <button
                type="button"
                onClick={() => setShowAll((v) => !v)}
                aria-expanded={showAll}
                className="flex w-full items-center justify-between rounded-xl border border-border bg-surface-raised px-5 py-4 text-left transition-colors hover:bg-surface-sunken"
              >
                <span>
                  <span className="text-title font-semibold text-foreground">
                    Every dependency we ship
                  </span>
                  <span className="ml-2 text-body text-foreground-muted">
                    {credits.dependencyCount} packages
                  </span>
                </span>
                <svg
                  className={`h-5 w-5 flex-shrink-0 text-foreground-muted transition-transform ${
                    showAll ? "rotate-180" : ""
                  }`}
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <path d="m6 9 6 6 6-6" />
                </svg>
              </button>

              {showAll && (
                <div className="mt-3 overflow-hidden rounded-xl border border-border bg-surface-raised">
                  <ul className="divide-y divide-border">
                    {credits.dependencies.map((d) => (
                      <li
                        key={d.name}
                        className="flex items-center justify-between gap-3 px-4 py-2.5"
                      >
                        <PackageLink name={d.name} repo={d.repo} />
                        <div className="flex flex-shrink-0 items-center gap-2">
                          <span className="font-mono text-meta text-foreground-muted">
                            {d.version}
                          </span>
                          <LicensePill license={d.license} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <p className="mt-3 text-meta text-foreground-muted">
                Generated from the installed packages on{" "}
                {new Date(credits.generatedAt).toLocaleDateString(undefined, {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
                . The same list lives in THIRD_PARTY_NOTICES in the source
                repository.
              </p>
            </section>
          </>
        )}
      </main>

      <MarketingFooter />
    </div>
  );
}

/** A featured callout for a recently added project. */
function FeaturedCard({
  title,
  license,
  href,
  body,
}: {
  title: string;
  license: string;
  href: string;
  body: string;
}) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="group block rounded-xl border border-sky-100 bg-sky-50/60 p-5 transition-colors hover:border-sky-200 hover:bg-sky-50 dark:hover:bg-brand-action/20"
    >
      <div className="mb-2 flex items-center gap-2">
        <span className="text-title font-semibold text-foreground group-hover:text-sky-800">
          {title}
          <ExternalIcon />
        </span>
        <LicensePill license={license} />
      </div>
      <p className="text-body leading-relaxed text-foreground-muted">{body}</p>
    </a>
  );
}
