"use client";

// Markdown embed hybrid, Phase 1. The Data Hub table block-embed renderer.
//
// Loaded lazily by ObjectEmbed for a `[caption](/datahub?doc=ID#ros=table)`
// embed. Reads the document's content (columns + rows) with a plain effect and
// renders a compact preview of the grid. A missing doc, or a non-table view we
// do not render yet (plot / result), degrades to the calm generic card.
//
// Voice: no em-dashes, no emojis, no mid-sentence colons.

import { useEffect, useState } from "react";
import { dataHubApi } from "@/lib/datahub/api";
import type { DataHubDocContent } from "@/lib/datahub/model/types";
import { renderPlot, readPlotSource } from "@/lib/datahub/plot-spec";
import { resultToText } from "@/lib/datahub/result-text";
import { plainLanguageSummary } from "@/lib/datahub/plain-language";
import type { NormalizedResult } from "@/lib/datahub/run-analysis";
import { objectDeepLink } from "@/lib/references";
import { ObjectEmbedCard, UnavailableEmbedCard, EmbedCaption, type EmbedRendererProps } from "./ObjectEmbed";

type LoadState =
  | { k: "loading" }
  | { k: "missing" }
  | { k: "ok"; content: DataHubDocContent };

/** Render a cell value as plain text. Table cells are scalars (string / number /
 *  null), so String() is safe; null / undefined show as empty. */
function cellText(value: unknown): string {
  if (value == null) return "";
  return String(value);
}

export default function DataHubEmbed({ descriptor, caption, figureLabel }: EmbedRendererProps) {
  const [state, setState] = useState<LoadState>({ k: "loading" });

  useEffect(() => {
    let cancelled = false;
    setState({ k: "loading" });
    dataHubApi
      .getContent(descriptor.id)
      .then((c) => {
        if (cancelled) return;
        setState(c ? { k: "ok", content: c } : { k: "missing" });
      })
      .catch(() => {
        if (!cancelled) setState({ k: "missing" });
      });
    return () => {
      cancelled = true;
    };
  }, [descriptor.id]);

  if (state.k === "loading") {
    return <ObjectEmbedCard descriptor={descriptor} caption={caption} loading />;
  }
  if (state.k === "missing") {
    return <UnavailableEmbedCard descriptor={descriptor} caption={caption} />;
  }

  // Plot view: render the figure SVG from the document's plot spec, reusing the
  // same pure renderPlot the Data Hub graph editor uses. The svg is generated by
  // our own deterministic geometry, so injecting it is safe.
  if (descriptor.view === "plot") {
    const plots = state.content.plots;
    const wanted = descriptor.opts.plot;
    const plot = (wanted ? plots.find((p) => p.id === wanted) : null) ?? plots[0];
    let svg = "";
    if (plot) {
      const analysisId = readPlotSource(plot).analysisId;
      const analysis = analysisId
        ? state.content.analyses.find((a) => a.id === analysisId) ?? null
        : null;
      try {
        svg = renderPlot(plot, state.content, analysis).svg;
      } catch {
        svg = "";
      }
    }
    if (!svg) {
      return <ObjectEmbedCard descriptor={descriptor} caption={caption} />;
    }
    const plotTitle = caption || plot?.name || state.content.meta.name;
    const plotHref = objectDeepLink("datahub", descriptor.id);
    return (
      <div>
        <div className="flex items-center gap-2 border-b border-border bg-surface-sunken px-3 py-2">
          <span className="truncate text-body font-semibold text-foreground">{plotTitle}</span>
          <span className="flex-1" />
          <a
            href={plotHref}
            className="shrink-0 rounded-md px-2 py-0.5 text-meta font-semibold text-foreground-muted transition-colors hover:text-foreground"
          >
            Open
          </a>
        </div>
        <div
          className="flex justify-center overflow-x-auto px-3 py-3"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <EmbedCaption
          caption={caption}
          name={plot?.name || state.content.meta.name}
          figureLabel={figureLabel}
        />
      </div>
    );
  }

  // Result view: render the analysis verdict + stats, reusing the same engine
  // formatters the Results sheet uses (plainLanguageSummary + resultToText).
  if (descriptor.view === "result") {
    const analysisId = descriptor.opts.analysis;
    const analysis = analysisId
      ? state.content.analyses.find((a) => a.id === analysisId)
      : state.content.analyses[0];
    const cache = analysis?.resultCache as
      | ({ ok?: boolean; kind?: string } | null)
      | undefined;
    if (!analysis || !cache || cache.ok === false || !cache.kind) {
      return <ObjectEmbedCard descriptor={descriptor} caption={caption} />;
    }
    let verdict = "";
    let table = "";
    try {
      verdict = plainLanguageSummary(cache as NormalizedResult);
      // resultToText is the verdict line, a blank line, then the stat table; we
      // show the verdict separately, so keep only the table portion here.
      table = resultToText(cache as NormalizedResult).split("\n").slice(2).join("\n");
    } catch {
      return <ObjectEmbedCard descriptor={descriptor} caption={caption} />;
    }
    const resultTitle = caption || analysis.name || state.content.meta.name;
    const resultHref = objectDeepLink("datahub", descriptor.id);
    return (
      <div>
        <div className="flex items-center gap-2 border-b border-border bg-surface-sunken px-3 py-2">
          <span className="truncate text-body font-semibold text-foreground">{resultTitle}</span>
          <span className="flex-1" />
          <a
            href={resultHref}
            className="shrink-0 rounded-md px-2 py-0.5 text-meta font-semibold text-foreground-muted transition-colors hover:text-foreground"
          >
            Open
          </a>
        </div>
        <div className="px-3 py-3">
          <p className="text-body text-foreground">{verdict}</p>
          {table.trim() ? (
            <pre className="mt-2 overflow-x-auto whitespace-pre text-meta font-mono text-foreground-muted">
              {table}
            </pre>
          ) : null}
        </div>
        <EmbedCaption
          caption={caption}
          name={analysis.name || state.content.meta.name}
          figureLabel={figureLabel}
        />
      </div>
    );
  }

  // Other non-table views have no dedicated renderer, so they show the calm card
  // rather than a misleading raw table.
  if (descriptor.view !== "table" && descriptor.view !== "summary") {
    return <ObjectEmbedCard descriptor={descriptor} caption={caption} />;
  }

  const { columns, rows } = state.content;
  const maxRows = descriptor.opts.rows ?? 6;
  const maxCols = descriptor.opts.cols ?? 6;
  const showCols = columns.slice(0, maxCols);
  const showRows = rows.slice(0, maxRows);
  const title = caption || state.content.meta.name;
  const href = objectDeepLink("datahub", descriptor.id);
  const dims = `${rows.length} ${rows.length === 1 ? "row" : "rows"} × ${columns.length} ${columns.length === 1 ? "col" : "cols"}`;

  return (
    <div>
      <div className="flex items-center gap-2 border-b border-border bg-surface-sunken px-3 py-2">
        <span className="truncate text-body font-semibold text-foreground">{title}</span>
        <span className="shrink-0 text-meta text-foreground-muted">{dims}</span>
        <span className="flex-1" />
        <a
          href={href}
          className="shrink-0 rounded-md px-2 py-0.5 text-meta font-semibold text-foreground-muted transition-colors hover:text-foreground"
        >
          Open
        </a>
      </div>
      <div className="overflow-x-auto px-3 py-2">
        <table className="w-full border-collapse text-meta">
          <thead>
            <tr>
              {showCols.map((c) => (
                <th
                  key={c.id}
                  className="border border-border bg-surface-sunken px-2 py-1 text-left font-semibold text-foreground-muted"
                >
                  {c.name}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {showRows.map((r) => (
              <tr key={r.id}>
                {showCols.map((c) => (
                  <td key={c.id} className="border border-border px-2 py-1 text-foreground">
                    {cellText(r.cells[c.id])}
                  </td>
                ))}
              </tr>
            ))}
            {rows.length > showRows.length ? (
              <tr>
                <td
                  colSpan={showCols.length}
                  className="border border-border px-2 py-1 text-center text-foreground-muted"
                >
                  {`+ ${rows.length - showRows.length} more rows`}
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
      <EmbedCaption caption={caption} name={state.content.meta.name} figureLabel={figureLabel} />
    </div>
  );
}
