import { describe, expect, it } from "vitest";

import { analyzeProtein, cleanProteinSeq } from "./protein";

/**
 * GOLDEN / GROUND-TRUTH suite for analyzeProtein.
 *
 * NO CIRCULAR TESTS. Every expected number below comes from an INDEPENDENT
 * outside authority, never from our own calculator's output. The authority is
 * Biopython's Bio.SeqUtils.ProtParam.ProteinAnalysis (plus
 * Bio.SeqUtils.molecular_weight and Bio.SeqUtils.IsoelectricPoint), the same
 * engine the ExPASy ProtParam web tool implements. The values are generated by
 * frontend/scripts/gen-protein-golden.py (committed alongside this file) so they
 * are reproducible and auditable: re-run that script in a venv with `biopython`
 * and confirm the constants here still match. This test itself is PURE (no
 * Python, no network) and CI-safe.
 *
 * RECONCILIATION GATE (see the script + the first test below): the dipeptide
 * "AG" has a hand-derivable average MW,
 *     mass(A) + mass(G) - 1*water = 89.0932 + 75.0666 - 18.0153 = 146.1445,
 * which equals Biopython's molecular_weight("AG","protein"). That confirms the
 * MW recipe our port uses before any larger sequence is trusted.
 *
 * TOLERANCE. Because analyzeProtein is a faithful line-by-line port of the
 * Biopython algorithms (verbatim constant tables), the two MUST agree to
 * floating-point precision. MW / instability / GRAVY / aromaticity / aliphatic
 * are asserted within 1e-3 absolute (well under 0.1%). pI is asserted within
 * 0.01 pH (the bisection tolerance is 1e-4, so this is generous slack on the
 * reported 2-decimal value). Extinction coefficients are exact integers. Any
 * case that exceeds tolerance is a PORT BUG, not a tolerance to relax.
 *
 * COVERAGE. Tiny hand-checkable peptides; the Biopython docstring pI anchors
 * PETER (4.53) and INGAR (9.75); extinction edge cases (no aromatics -> 0, Tyr
 * only, Trp only, with/without cystines, odd Cys count); acidic vs basic
 * sequences spanning the pI range; and three real proteins (human insulin A
 * chain, EGFP, bovine serum albumin mature chain).
 */

interface Golden {
  id: string;
  seq: string;
  mw: number;
  pi: number;
  epsReduced: number;
  epsOxidized: number;
  a280Reduced: number;
  a280Oxidized: number;
  /** null where Biopython could not compute it (never happens for these). */
  instability: number | null;
  gravy: number;
  aromaticity: number;
  aliphatic: number;
}

const SEQS: Record<string, string> = {
  dipeptide_AG: "AG",
  peter: "PETER",
  ingar: "INGAR",
  no_aromatics: "AGGAGGAGGAGG",
  only_tyr: "AYAYAYA",
  only_trp: "AWAWAWA",
  with_cystines: "ACACACACAC",
  odd_cysteine: "ACACACAC",
  acidic: "DDDEEEDDDEEE",
  basic: "KKKRRRKKKRRR",
  mixed_charge: "DEKRHCYDEKRHCY",
  insulin_a_chain: "GIVEQCCTSICSLYQLENYCN",
  egfp:
    "MVSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLT" +
    "YGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFK" +
    "EDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPD" +
    "NHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITLGMDELYK",
  bsa:
    "DTHKSEIAHRFKDLGEEHFKGLVLIAFSQYLQQCPFDEHVKLVNELTEFAKTCVADESHAGCEKSL" +
    "HTLFGDELCKVASLRETYGDMADCCEKQEPERNECFLSHKDDSPDLPKLKPDPNTLCDEFKADEKK" +
    "FWGKYLYEIARRHPYFYAPELLYYANKYNGVFQECCQAEDKGACLLPKIETMREKVLASSARQRLR" +
    "CASIQKFGERALKAWSVARLSQKFPKAEFVEVTKLVTDLTKVHKECCHGDLLECADDRADLAKYIC" +
    "DNQDTISSKLKECCDKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYQEAKDAFLGSFL" +
    "YEYSRRHPEYAVSVLLRLAKEYEATLEECCAKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEK" +
    "LGEYGFQNALIVRYTRKVPQVSTPTLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLILNRLCVL" +
    "HEKTPVSEKVTKCCTESLVNRRPCFSALTPDETYVPKAFDEKLFTFHADICTLPDTEKQIKKQTAL" +
    "VELLKHKPKATEEQLKTVMENFVAFVDKCCAADDKEACFAVEGPKLVVSTQTALA",
};

// --- Biopython ground-truth values (from gen-protein-golden.py) ---
const GOLDEN: Golden[] = [
  { id: "dipeptide_AG", seq: SEQS.dipeptide_AG, mw: 146.1445, pi: 5.5700, epsReduced: 0, epsOxidized: 0, a280Reduced: 0.000000, a280Oxidized: 0.000000, instability: 5.000000, gravy: 0.700000, aromaticity: 0.000000, aliphatic: 50.0000 },
  { id: "peter", seq: SEQS.peter, mw: 630.6481, pi: 4.5321, epsReduced: 0, epsOxidized: 0, a280Reduced: 0.000000, a280Oxidized: 0.000000, instability: 81.280000, gravy: -2.760000, aromaticity: 0.000000, aliphatic: 0.0000 },
  { id: "ingar", seq: SEQS.ingar, mw: 529.5904, pi: 9.7500, epsReduced: 0, epsOxidized: 0, a280Reduced: 0.000000, a280Oxidized: 0.000000, instability: -39.040000, gravy: -0.420000, aromaticity: 0.000000, aliphatic: 98.0000 },
  { id: "no_aromatics", seq: SEQS.no_aromatics, mw: 758.7373, pi: 5.5700, epsReduced: 0, epsOxidized: 0, a280Reduced: 0.000000, a280Oxidized: 0.000000, instability: 29.075000, gravy: 0.333333, aromaticity: 0.000000, aliphatic: 33.3333 },
  { id: "only_tyr", seq: SEQS.only_tyr, mw: 791.8465, pi: 5.5675, epsReduced: 4470, epsOxidized: 4470, a280Reduced: 5.645033, a280Oxidized: 5.645033, instability: 110.057143, gravy: 0.471429, aromaticity: 0.428571, aliphatic: 57.1429 },
  { id: "only_trp", seq: SEQS.only_trp, mw: 860.9566, pi: 5.5700, epsReduced: 16500, epsOxidized: 16500, a280Reduced: 19.164729, a280Oxidized: 19.164729, instability: -55.842857, gravy: 0.642857, aromaticity: 0.428571, aliphatic: 57.1429 },
  { id: "with_cystines", seq: SEQS.with_cystines, mw: 889.1193, pi: 5.5307, epsReduced: 0, epsOxidized: 250, a280Reduced: 0.000000, a280Oxidized: 0.281177, instability: 228.700000, gravy: 2.150000, aromaticity: 0.000000, aliphatic: 50.0000 },
  { id: "odd_cysteine", seq: SEQS.odd_cysteine, mw: 714.8985, pi: 5.5380, epsReduced: 0, epsOxidized: 250, a280Reduced: 0.000000, a280Oxidized: 0.349700, instability: 228.450000, gravy: 2.150000, aromaticity: 0.000000, aliphatic: 50.0000 },
  { id: "acidic", seq: SEQS.acidic, mw: 1483.2237, pi: 4.0500, epsReduced: 0, epsOxidized: 0, a280Reduced: 0.000000, a280Oxidized: 0.000000, instability: 133.883333, gravy: -3.500000, aromaticity: 0.000000, aliphatic: 0.0000 },
  { id: "basic", seq: SEQS.basic, mw: 1724.1633, pi: 12.0000, epsReduced: 0, epsOxidized: 0, a280Reduced: 0.000000, a280Oxidized: 0.000000, instability: 254.433333, gravy: -4.200000, aromaticity: 0.000000, aliphatic: 0.0000 },
  { id: "mixed_charge", seq: SEQS.mixed_charge, mw: 1882.0449, pi: 6.9060, epsReduced: 2980, epsOxidized: 3105, a280Reduced: 1.583384, a280Oxidized: 1.649801, instability: 100.285714, gravy: -2.485714, aromaticity: 0.142857, aliphatic: 0.0000 },
  { id: "insulin_a_chain", seq: SEQS.insulin_a_chain, mw: 2383.6961, pi: 4.0500, epsReduced: 2980, epsOxidized: 3230, a280Reduced: 1.250159, a280Oxidized: 1.355039, instability: 22.542857, gravy: 0.214286, aromaticity: 0.095238, aliphatic: 88.0952 },
  { id: "egfp", seq: SEQS.egfp, mw: 26941.1543, pi: 5.5836, epsReduced: 21890, epsOxidized: 22015, a280Reduced: 0.812512, a280Oxidized: 0.817151, instability: 29.052720, gravy: -0.467364, aromaticity: 0.100418, aliphatic: 79.0377 },
  { id: "bsa", seq: SEQS.bsa, mw: 66432.2613, pi: 5.5987, epsReduced: 40800, epsOxidized: 42925, a280Reduced: 0.614159, a280Oxidized: 0.646147, instability: 40.109108, gravy: -0.474614, aromaticity: 0.084048, aliphatic: 76.1407 },
];

const TOL_ABS = 1e-3; // MW / instability / GRAVY / aromaticity / aliphatic
const TOL_PI = 0.01; // pH units
const TOL_A280 = 1e-4; // derived ratio, slightly looser rounding

describe("analyzeProtein — Biopython ProtParam parity (faithful port)", () => {
  for (const g of GOLDEN) {
    it(`${g.id} (len ${g.seq.length}) matches Biopython`, () => {
      const r = analyzeProtein(g.seq);
      expect(r, `${g.id}: returned null`).not.toBeNull();
      const a = r!;

      // Length: clean sequence length (no non-standard chars in fixtures).
      expect(a.length, `${g.id}: length`).toBe(g.seq.length);

      // Molecular weight — tight (faithful sum-minus-water recipe).
      expect(
        Math.abs(a.molecularWeight - g.mw),
        `PORT BUG: ${g.id} MW ours=${a.molecularWeight.toFixed(4)} vs Biopython=${g.mw}`,
      ).toBeLessThanOrEqual(TOL_ABS);

      // Isoelectric point — bisection parity.
      expect(
        Math.abs(a.isoelectricPoint - g.pi),
        `PORT BUG: ${g.id} pI ours=${a.isoelectricPoint.toFixed(4)} vs Biopython=${g.pi}`,
      ).toBeLessThanOrEqual(TOL_PI);

      // Extinction coefficients — exact integers.
      expect(a.extinctionReduced, `${g.id} eps reduced`).toBe(g.epsReduced);
      expect(a.extinctionOxidized, `${g.id} eps oxidized`).toBe(g.epsOxidized);

      // A280 of a 1 g/L solution = eps / MW.
      expect(
        Math.abs(a.a280Reduced - g.a280Reduced),
        `${g.id} A280 reduced`,
      ).toBeLessThanOrEqual(TOL_A280);
      expect(
        Math.abs(a.a280Oxidized - g.a280Oxidized),
        `${g.id} A280 oxidized`,
      ).toBeLessThanOrEqual(TOL_A280);

      // Instability index (Guruprasad DIWV).
      if (g.instability !== null) {
        expect(
          Math.abs(a.instabilityIndex - g.instability),
          `PORT BUG: ${g.id} instability ours=${a.instabilityIndex.toFixed(4)} vs Biopython=${g.instability}`,
        ).toBeLessThanOrEqual(TOL_ABS);
      }

      // GRAVY (Kyte-Doolittle).
      expect(
        Math.abs(a.gravy - g.gravy),
        `PORT BUG: ${g.id} GRAVY ours=${a.gravy.toFixed(4)} vs Biopython=${g.gravy}`,
      ).toBeLessThanOrEqual(TOL_ABS);

      // Aromaticity (Lobry).
      expect(
        Math.abs(a.aromaticity - g.aromaticity),
        `${g.id} aromaticity`,
      ).toBeLessThanOrEqual(TOL_ABS);

      // Aliphatic index (Ikai closed form).
      expect(
        Math.abs(a.aliphaticIndex - g.aliphatic),
        `${g.id} aliphatic index`,
      ).toBeLessThanOrEqual(TOL_ABS);
    });
  }
});

describe("analyzeProtein — reconciliation gate + published anchors", () => {
  it("dipeptide AG MW == hand value 146.1445 (== Biopython)", () => {
    // mass(A)=89.0932 + mass(G)=75.0666 - water=18.0153 = 146.1445
    const r = analyzeProtein("AG")!;
    expect(r.molecularWeight).toBeCloseTo(146.1445, 4);
  });

  it("PETER pI == 4.53 (Biopython ProtParam docstring)", () => {
    const r = analyzeProtein("PETER")!;
    expect(r.isoelectricPoint).toBeCloseTo(4.53, 2);
  });

  it("INGAR pI == 9.75 (Biopython IsoelectricPoint docstring)", () => {
    const r = analyzeProtein("INGAR")!;
    expect(r.isoelectricPoint).toBeCloseTo(9.75, 2);
  });
});

describe("analyzeProtein — convention + guards", () => {
  it("returns null when no standard residue is present", () => {
    expect(analyzeProtein("")).toBeNull();
    expect(analyzeProtein("   \n 123 ")).toBeNull();
    expect(analyzeProtein("123 -- *")).toBeNull(); // digits / gaps / stop only
    expect(analyzeProtein("BZXU O")).toBeNull(); // all non-standard residues
  });

  it("ignores whitespace, lowercases, and strips a FASTA header line content", () => {
    // Lowercase + internal whitespace must not change the result.
    const spaced = analyzeProtein("p e t e r");
    const lower = analyzeProtein("peter");
    expect(spaced).not.toBeNull();
    expect(spaced!.molecularWeight).toBeCloseTo(lower!.molecularWeight, 6);
    expect(spaced!.isoelectricPoint).toBeCloseTo(lower!.isoelectricPoint, 6);
  });

  it("flags non-standard / ambiguous residues and excludes them from the math", () => {
    const { clean, nonStandard } = cleanProteinSeq("ACXBZU*OJ-DE");
    expect(clean).toBe("ACDE");
    // X B Z U O J * are all flagged; gap/punctuation are silently dropped.
    expect(nonStandard).toEqual(["*", "B", "J", "O", "U", "X", "Z"]);
    const r = analyzeProtein("ACXBZU*OJ-DE")!;
    expect(r.length).toBe(4);
    expect(r.nonStandardChars).toContain("X");
  });

  it("extinction coefficient is zero when there are no Trp/Tyr/Cys", () => {
    const r = analyzeProtein("AGGAGGAGGAGG")!;
    expect(r.extinctionReduced).toBe(0);
    expect(r.extinctionOxidized).toBe(0);
    expect(r.a280Reduced).toBe(0);
  });

  it("composition counts sum to length and percentages to ~100", () => {
    const r = analyzeProtein("INGAR")!;
    const totalCount = r.composition.reduce((s, c) => s + c.count, 0);
    expect(totalCount).toBe(r.length);
    const totalPct = r.composition.reduce((s, c) => s + c.percent, 0);
    expect(totalPct).toBeCloseTo(100, 6);
  });
});
