// Canonical institution registry resolver (social layer).
//
// Pure, server-side lookups over a pre-built static asset derived from the
// Research Organization Registry (ROR, https://ror.org, CC0). The asset is a
// gzipped JSON generated by scripts/build-institution-registry.mjs and HOSTED
// ON CLOUDFLARE R2 (never committed to git, never in a function bundle). It is
// fetched once server-side and cached in module scope. See the build script for
// the schema; this module only READS it.
//
// Why R2 + server-side: the asset is ~28 MB raw (~6 MB gzipped). Committing it
// would bloat git history forever, and reading public/ via fs fails on Vercel
// (public assets are not in the serverless function filesystem). Fetching from
// R2 once and caching avoids both: nothing in git, nothing in the client bundle,
// and the read works in prod. Uses node-only APIs (aws-sdk, zlib), so importing
// this from a client component fails the build, which is the intended guard.
//
// Unknown domain or unreachable R2 -> null, so every caller falls back to the
// existing humanizeInstitutionSlug behavior unchanged.
//
// SCOPE NOTE: this module is the ONE helper Popup Unifier may import to expand
// the directory WHERE clause to a domain cluster (clusterDomainsFor). It builds
// its OWN R2 client from the shared R2_ env and does NOT import lib/sharing/**
// or app/api/directory/**.
//
// House style: no em-dashes, no emojis, no mid-sentence colons.

import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { gunzipSync } from "node:zlib";

export interface InstitutionRecord {
  /** The website domain this entry is keyed by (lowercased). */
  domain: string;
  /** Clean canonical name from ROR (e.g. "University of Wisconsin-Madison"). */
  canonicalName: string;
  /** The ROR id, e.g. "https://ror.org/01y2jtd41". */
  rorId: string;
  /** ISO country name from the org's first location, or null. */
  country: string | null;
  /** Alternate names (aliases/labels/acronyms) from ROR. */
  aliases: string[];
  /** Every domain that maps to the same org (parent + child/related + subdomains). */
  clusterDomains: string[];
}

interface RegistryFile {
  meta: Record<string, unknown>;
  byDomain: Record<string, InstitutionRecord>;
}

const EMPTY: RegistryFile = { meta: {}, byDomain: {} };

// The R2 object key for the gzipped registry. Re-upload to the same key on a new
// ROR release (or bump via env). The bucket + creds are the shared R2_ env that
// the rest of the app already uses.
const REGISTRY_KEY =
  process.env.INSTITUTION_REGISTRY_R2_KEY ??
  "institution-registry/current.json.gz";

// Module-scope cache. Set ONLY on a successful load, so a transient R2 miss (for
// example before the asset is uploaded) does not pin an empty registry for the
// life of the instance: the next lookup retries. A successful load is reused for
// the life of the server process.
let cache: RegistryFile | null = null;
let inFlight: Promise<RegistryFile> | null = null;

function getR2(): S3Client | null {
  const accountId = process.env.R2_ACCOUNT_ID;
  const accessKeyId = process.env.R2_ACCESS_KEY_ID;
  const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY;
  if (!accountId || !accessKeyId || !secretAccessKey) return null;
  return new S3Client({
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    region: "auto",
    credentials: { accessKeyId, secretAccessKey },
  });
}

async function fetchRegistry(): Promise<RegistryFile> {
  const bucket = process.env.R2_BUCKET;
  const s3 = getR2();
  if (!bucket || !s3) return EMPTY;
  const res = await s3.send(
    new GetObjectCommand({ Bucket: bucket, Key: REGISTRY_KEY }),
  );
  if (!res.Body) return EMPTY;
  const gz = await res.Body.transformToByteArray();
  const raw = gunzipSync(Buffer.from(gz)).toString("utf8");
  const parsed = JSON.parse(raw) as RegistryFile;
  return parsed && parsed.byDomain ? parsed : EMPTY;
}

async function loadRegistry(): Promise<RegistryFile> {
  if (cache) return cache;
  if (!inFlight) {
    inFlight = fetchRegistry()
      .then((reg) => {
        if (reg !== EMPTY) cache = reg;
        return reg;
      })
      .catch(() => EMPTY)
      .finally(() => {
        inFlight = null;
      });
  }
  return inFlight;
}

/**
 * Test/SSR seam: inject a registry directly (e.g. a small fixture) instead of
 * fetching from R2. Pass null to reset back to lazy loading.
 */
export function __setRegistryForTests(reg: RegistryFile | null): void {
  cache = reg;
  inFlight = null;
}

/**
 * Normalizes a slug or domain into the domain-shaped key the registry uses.
 * The public /institution/[slug] slug IS the verified email domain, so this is
 * mostly a lowercase + trim + strip of scheme/path/leading-www, tolerant of a
 * full URL or an email-like input. Returns "" when nothing usable remains.
 */
export function normalizeInstitutionSlug(input: string): string {
  if (!input || typeof input !== "string") return "";
  let h = input.trim().toLowerCase();
  if (!h) return "";
  if (h.includes("@")) h = h.split("@").pop() as string;
  h = h.replace(/^[a-z][a-z0-9+.-]*:\/\//, "");
  h = h.split("/")[0];
  h = h.split("?")[0];
  h = h.split("#")[0];
  h = h.split(":")[0];
  h = h.replace(/^www\./, "");
  h = h.replace(/\.$/, "");
  return h;
}

/**
 * Resolves a slug or domain to its canonical institution record, or null when
 * the registry has no entry (or R2 is unreachable). Callers fall back to
 * humanizeInstitutionSlug on null. Server-side only.
 */
export async function resolveInstitution(
  slugOrDomain: string,
): Promise<InstitutionRecord | null> {
  const key = normalizeInstitutionSlug(slugOrDomain);
  if (!key) return null;
  const reg = await loadRegistry();
  return reg.byDomain[key] ?? null;
}

/**
 * Returns every domain that belongs to the same institution as `domain`,
 * including `domain` itself, sorted and de-duplicated. When the domain is not in
 * the registry (or R2 is unreachable) the result is just `[normalized(domain)]`
 * (or [] for empty input), so a caller can always safely IN()-filter against it.
 *
 * This is the helper the directory layer (Popup Unifier) imports to widen
 * getInstitutionByDomain from `= $domain` to `IN (await clusterDomainsFor($domain))`,
 * so one institution page aggregates all its verified subdomains.
 */
export async function clusterDomainsFor(domain: string): Promise<string[]> {
  const key = normalizeInstitutionSlug(domain);
  if (!key) return [];
  const reg = await loadRegistry();
  const rec = reg.byDomain[key];
  if (!rec) return [key];
  const all = new Set<string>(rec.clusterDomains);
  all.add(key);
  return [...all].sort();
}
