import JSZip from "jszip";
import TurndownService from "turndown";
import type {
  MissingInlineImage,
  ParsedAttachment,
  ParsedEntry,
  ParsedEntryType,
  ParsedNode,
  ParsedNotebook,
  ParsedPage,
} from "../types";

const SOURCE = "labarchives-offline-zip";

const DISPATCH_SET_ENTRY_RE =
  /dispatchSetEntry\("(\d+)",\s*decodeBase64AndParseJSON\("([^"]+)"\)\)/g;

const PAGE_DEDUP_DIV_RE = /<div id="([A-Za-z0-9+/=]{12,})"[^>]*>/;

const META_DESCRIPTION_RE =
  /<meta\s+name="Description"\s+content="([^"]+)"\s*\/?>/i;

const NAVTREE_HTML_RE = /<div id="navtree">([\s\S]*?)<\/div>/i;

const HEADER_BREADCRUMB_RE =
  /<span style="font-weight:normal">([^<]+)<\/span>([^<]*)/;

const GENERATED_BY_RE =
  /generated by\s+([^\n<]+?)\s+on\s+([^\n<]+?)\s*<\/div>/i;

const FROALA_COMMENT_RE = /<!--RTE_[A-Za-z0-9_]+(?:\{[^}]*\})?-->/g;
const FR_ORIGINAL_STYLE_RE = /\s+fr-original-style="[^"]*"/g;
const FR_ORIGINAL_CLASS_RE = /\s+fr-original-class="[^"]*"/g;

const IMG_TAG_RE = /<img\b[^>]*\bsrc="([^"]+)"[^>]*>/gi;

const FORM_A_INLINE_PREFIX = "attachments/inline/";
const FORM_B_INLINE_PREFIX = "/attachments/inline_image/";

interface RawEntryPayload {
  type?: number;
  data?: string;
  filename?: string;
  fileSize?: number;
  isImage?: boolean;
  urls?: { urlLink?: string; urlDownload?: string };
  lastModifiedBy?: string;
  updatedAt?: string;
  tags?: unknown;
}

export async function parseLabArchivesOfflineZip(
  input: File | ArrayBuffer,
): Promise<ParsedNotebook> {
  const zip = await JSZip.loadAsync(input);

  const homeFile = zip.file("notebook_home_page.html");
  if (!homeFile) {
    throw new Error(
      "ZIP is missing notebook_home_page.html — does not look like a LabArchives offline export.",
    );
  }
  const homeHtml = await homeFile.async("string");

  const { notebookName, rootBreadcrumb } = parseNotebookHeader(homeHtml);
  const { exportedBy, exportedAt } = parseGeneratedBy(homeHtml);
  const tree = parseNavTree(homeHtml);

  const pageFlat = collectPages(tree);
  const ancestors: string[] = [];
  if (notebookName !== null) ancestors.push(notebookName);
  ancestors.push(...rootBreadcrumb);

  const pages: ParsedPage[] = [];
  const notebookMissing: MissingInlineImage[] = [];

  for (const { node, pathInTree } of pageFlat) {
    if (!node.pageFile) continue;
    const pageEntry = zip.file(node.pageFile);
    if (!pageEntry) continue;
    const html = await pageEntry.async("string");
    const treePath = [...ancestors, ...pathInTree];

    const page = parsePage({
      html,
      pageId: pageIdFromFile(node.pageFile),
      pageFile: node.pageFile,
      treePath,
      zip,
    });
    pages.push(page);
    notebookMissing.push(...collectEntryMissing(page));
  }

  return {
    source: SOURCE,
    notebookName,
    rootBreadcrumb,
    exportedBy,
    exportedAt,
    tree,
    pages,
    missingInlineImages: notebookMissing,
  };
}

function parseNotebookHeader(html: string): {
  notebookName: string | null;
  rootBreadcrumb: string[];
} {
  const m = HEADER_BREADCRUMB_RE.exec(html);
  if (!m) return { notebookName: null, rootBreadcrumb: [] };
  const notebookName = decodeEntities(m[1]).trim();
  const rest = decodeEntities(m[2]).trim();
  const breadcrumb = rest
    .replace(/^\//, "")
    .split("/")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
  return { notebookName: notebookName || null, rootBreadcrumb: breadcrumb };
}

function parseGeneratedBy(html: string): {
  exportedBy: string | null;
  exportedAt: string | null;
} {
  const m = GENERATED_BY_RE.exec(html);
  if (!m) return { exportedBy: null, exportedAt: null };
  const name = decodeEntities(m[1]).trim();
  const dateStr = decodeEntities(m[2]).trim();
  return {
    exportedBy: name || null,
    exportedAt: parseLabArchivesDate(dateStr),
  };
}

function parseLabArchivesDate(s: string): string | null {
  const cleaned = s
    .replace(/\s+@/, " ")
    .replace(/\s+([A-Z]{2,5})$/, " $1");
  const tzMap: Record<string, string> = {
    EST: "-0500",
    EDT: "-0400",
    CST: "-0600",
    CDT: "-0500",
    MST: "-0700",
    MDT: "-0600",
    PST: "-0800",
    PDT: "-0700",
    UTC: "+0000",
    GMT: "+0000",
  };
  const withOffset = cleaned.replace(
    /\s+(EST|EDT|CST|CDT|MST|MDT|PST|PDT|UTC|GMT)$/,
    (_, tz: string) => ` ${tzMap[tz] ?? "+0000"}`,
  );
  const t = Date.parse(withOffset);
  if (Number.isFinite(t)) return new Date(t).toISOString();
  const t2 = Date.parse(s);
  if (Number.isFinite(t2)) return new Date(t2).toISOString();
  return null;
}

function parseNavTree(html: string): ParsedNode[] {
  const navMatch = NAVTREE_HTML_RE.exec(html);
  if (!navMatch) return [];
  const navHtml = navMatch[1];
  const parser = getDomParser();
  const doc = parser.parseFromString(`<div>${navHtml}</div>`, "text/html");
  const rootUl = doc.querySelector("div > ul");
  if (!rootUl) return [];
  return walkUl(rootUl);
}

function walkUl(ul: Element): ParsedNode[] {
  const nodes: ParsedNode[] = [];
  for (const li of Array.from(ul.children)) {
    if (li.tagName.toUpperCase() !== "LI") continue;
    const id = li.getAttribute("id") ?? "";
    const rel = (li.getAttribute("rel") ?? "").toLowerCase();
    const anchor = li.querySelector("a");
    const name = (anchor?.textContent ?? "").trim();
    if (rel === "page") {
      const href = anchor?.getAttribute("href") ?? "";
      nodes.push({
        treeNodeId: id,
        kind: "page",
        name,
        pageFile: href || undefined,
      });
    } else {
      const childUl = li.querySelector("ul");
      const children = childUl ? walkUl(childUl) : [];
      nodes.push({
        treeNodeId: id,
        kind: "folder",
        name,
        children,
      });
    }
  }
  return nodes;
}

function collectPages(
  nodes: ParsedNode[],
  trail: string[] = [],
): { node: ParsedNode; pathInTree: string[] }[] {
  const out: { node: ParsedNode; pathInTree: string[] }[] = [];
  for (const node of nodes) {
    const here = [...trail, node.name];
    if (node.kind === "page") {
      out.push({ node, pathInTree: here });
    } else if (node.children) {
      out.push(...collectPages(node.children, here));
    }
  }
  return out;
}

function pageIdFromFile(file: string): string {
  const m = /^(\d+)\.html$/.exec(file);
  return m ? m[1] : file.replace(/\.html$/, "");
}

interface ParsePageInput {
  html: string;
  pageId: string;
  pageFile: string;
  treePath: string[];
  zip: JSZip;
}

function parsePage({
  html,
  pageId,
  pageFile,
  treePath,
  zip,
}: ParsePageInput): ParsedPage {
  const { pageDedupRaw, notebookId } = parsePageDedup(html);
  const { pageCreator, pageCreatedAt } = parsePageMeta(html);

  const entries: ParsedEntry[] = [];
  const reusable = new RegExp(DISPATCH_SET_ENTRY_RE.source, "g");
  let m: RegExpExecArray | null;
  while ((m = reusable.exec(html)) !== null) {
    const entryId = m[1];
    const b64 = m[2];
    let payload: RawEntryPayload | null = null;
    try {
      const json = decodeBase64Utf8(b64);
      payload = JSON.parse(json) as RawEntryPayload;
    } catch {
      payload = null;
    }
    if (!payload) continue;
    entries.push(
      buildEntry({
        entryId,
        payload,
        notebookId,
        pageId,
        zip,
      }),
    );
  }

  return {
    pageId,
    pageFile,
    treePath,
    pageCreator,
    pageCreatedAt,
    pageDedupRaw,
    notebookId,
    entries,
  };
}

function parsePageDedup(html: string): {
  pageDedupRaw: string | null;
  notebookId: string | null;
} {
  const m = PAGE_DEDUP_DIV_RE.exec(html);
  if (!m) return { pageDedupRaw: null, notebookId: null };
  let decoded: string;
  try {
    decoded = decodeBase64Utf8(m[1]);
  } catch {
    return { pageDedupRaw: null, notebookId: null };
  }
  const parts = decoded.split("|");
  if (parts.length < 2) return { pageDedupRaw: decoded, notebookId: null };
  const middle = parts[1].split("/");
  const notebookId = middle.length > 0 ? middle[0] : null;
  return { pageDedupRaw: decoded, notebookId };
}

function parsePageMeta(html: string): {
  pageCreator: string | null;
  pageCreatedAt: string | null;
} {
  const m = META_DESCRIPTION_RE.exec(html);
  if (!m) return { pageCreator: null, pageCreatedAt: null };
  const content = decodeEntities(m[1]);
  const dashIdx = content.lastIndexOf(" - ");
  if (dashIdx < 0) return { pageCreator: null, pageCreatedAt: null };
  const tail = content.slice(dashIdx + 3);
  const byMatch = /created by\s+(.+?)\s+on\s+(.+)$/i.exec(tail);
  if (!byMatch) return { pageCreator: null, pageCreatedAt: null };
  const creator = byMatch[1].trim();
  const dateStr = byMatch[2].trim();
  const t = Date.parse(dateStr);
  const iso = Number.isFinite(t) ? new Date(t).toISOString() : null;
  return { pageCreator: creator || null, pageCreatedAt: iso };
}

interface BuildEntryInput {
  entryId: string;
  payload: RawEntryPayload;
  notebookId: string | null;
  pageId: string;
  zip: JSZip;
}

function buildEntry({
  entryId,
  payload,
  notebookId,
  pageId,
  zip,
}: BuildEntryInput): ParsedEntry {
  const rawTypeNumber = typeof payload.type === "number" ? payload.type : -1;
  const type = mapEntryType(rawTypeNumber);
  const author = stringOrNull(payload.lastModifiedBy);
  const updatedAt = stringOrNull(payload.updatedAt);
  const tags = Array.isArray(payload.tags)
    ? (payload.tags as unknown[]).filter(
        (x): x is string => typeof x === "string",
      )
    : [];
  const dedupKey = composeDedupKey({
    notebookId,
    pageId,
    entryId,
  });

  const attachments: ParsedAttachment[] = [];
  const missingInlineImages: MissingInlineImage[] = [];
  let bodyMarkdown: string | null = null;
  let unsupportedRaw: unknown | undefined;

  switch (type) {
    case "text": {
      const data = typeof payload.data === "string" ? payload.data : "";
      const rewritten = rewriteInlineImages({
        html: data,
        zip,
        attachments,
        missingInlineImages,
      });
      const cleaned = cleanFroalaHtml(rewritten);
      bodyMarkdown = htmlToMarkdown(cleaned);
      break;
    }
    case "heading": {
      const data = typeof payload.data === "string" ? payload.data : "";
      bodyMarkdown = `# ${data}`;
      break;
    }
    case "plain_text": {
      bodyMarkdown = typeof payload.data === "string" ? payload.data : "";
      break;
    }
    case "attachment": {
      const att = buildBodyAttachment(payload, zip);
      if (att) attachments.push(att);
      break;
    }
    case "unsupported":
      unsupportedRaw = payload;
      break;
  }

  const entry: ParsedEntry = {
    entryId,
    dedupKey,
    type,
    rawTypeNumber,
    author,
    updatedAt,
    bodyMarkdown,
    attachments,
    missingInlineImages,
    tags,
  };
  if (unsupportedRaw !== undefined) entry.unsupportedRaw = unsupportedRaw;
  return entry;
}

function mapEntryType(n: number): ParsedEntryType {
  switch (n) {
    case 1:
      return "text";
    case 2:
      return "attachment";
    case 4:
      return "heading";
    case 5:
      return "plain_text";
    default:
      return "unsupported";
  }
}

function composeDedupKey({
  notebookId,
  pageId,
  entryId,
}: {
  notebookId: string | null;
  pageId: string;
  entryId: string;
}): string {
  if (notebookId && pageId && entryId) {
    return `${notebookId}/${pageId}/Entry/${entryId}`;
  }
  return `${SOURCE}-${pageId}-${entryId}`;
}

function buildBodyAttachment(
  payload: RawEntryPayload,
  zip: JSZip,
): ParsedAttachment | null {
  const filename = stringOrNull(payload.filename);
  const link = stringOrNull(payload.urls?.urlLink);
  if (!filename || !link) return null;
  const fileSize = typeof payload.fileSize === "number" ? payload.fileSize : 0;
  const isImage = payload.isImage === true;
  return makeAttachment({
    filename,
    fileSize,
    isImage,
    usage: "body",
    zipPath: link,
    zip,
  });
}

interface RewriteContext {
  html: string;
  zip: JSZip;
  attachments: ParsedAttachment[];
  missingInlineImages: MissingInlineImage[];
}

function rewriteInlineImages(ctx: RewriteContext): string {
  return ctx.html.replace(IMG_TAG_RE, (full, srcRaw: string) => {
    const src = decodeEntities(srcRaw);
    if (src.startsWith(FORM_A_INLINE_PREFIX)) {
      const filename = basename(src);
      ctx.attachments.push(
        makeAttachment({
          filename,
          fileSize: 0,
          isImage: true,
          usage: "inline",
          zipPath: src,
          zip: ctx.zip,
        }),
      );
      return `<img src="Images/${filename}" alt="">`;
    }
    if (src.startsWith(FORM_B_INLINE_PREFIX)) {
      const missing = decodeFormBImage(src);
      ctx.missingInlineImages.push(missing);
      return `<img src="Images/missing-${missing.filename}" alt="">`;
    }
    return full;
  });
}

function decodeFormBImage(src: string): MissingInlineImage {
  const queryIdx = src.indexOf("?");
  const beforeQuery = queryIdx >= 0 ? src.slice(0, queryIdx) : src;
  const query = queryIdx >= 0 ? src.slice(queryIdx + 1) : "";
  const params = parseQuery(query);
  const epIdEncoded = params.get("ep_id") ?? "";
  const fileNameParam = params.get("file_name") ?? "";

  let revision: string | undefined;
  let notebookId: string | undefined;
  let pageId: string | undefined;
  let entryPartId: string | undefined;
  let version: string | undefined;
  if (epIdEncoded) {
    try {
      const decoded = decodeBase64Utf8(epIdEncoded);
      const parts = decoded.split("|");
      if (parts.length === 3) {
        revision = parts[0];
        version = parts[2];
        const middle = parts[1].split("/");
        if (middle.length >= 4) {
          notebookId = middle[0];
          pageId = middle[1];
          entryPartId = middle[3];
        }
      }
    } catch {
      // leave undefined; originalUrl is preserved
    }
  }

  const filename =
    fileNameParam ||
    (entryPartId ? `${entryPartId}.bin` : `${basename(beforeQuery)}.bin`);

  return {
    filename,
    originalUrl: src,
    notebookId,
    pageId,
    entryPartId,
    revision,
    version,
  };
}

function parseQuery(q: string): Map<string, string> {
  const out = new Map<string, string>();
  if (!q) return out;
  for (const pair of q.split("&")) {
    if (!pair) continue;
    const eq = pair.indexOf("=");
    if (eq < 0) {
      out.set(decodeURIComponent(pair), "");
    } else {
      const k = decodeURIComponent(pair.slice(0, eq));
      const v = decodeURIComponent(pair.slice(eq + 1));
      out.set(k, v);
    }
  }
  return out;
}

function cleanFroalaHtml(html: string): string {
  return html
    .replace(FROALA_COMMENT_RE, "")
    .replace(FR_ORIGINAL_STYLE_RE, "")
    .replace(FR_ORIGINAL_CLASS_RE, "");
}

let turndown: TurndownService | null = null;
function htmlToMarkdown(html: string): string {
  if (!turndown) {
    turndown = new TurndownService({
      headingStyle: "atx",
      codeBlockStyle: "fenced",
      bulletListMarker: "-",
      emDelimiter: "_",
    });
    turndown.keep(["sub", "sup"]);
  }
  return turndown.turndown(html).trim();
}

function makeAttachment(args: {
  filename: string;
  fileSize: number;
  isImage: boolean;
  usage: "body" | "inline";
  zipPath: string;
  zip: JSZip;
}): ParsedAttachment {
  const { zip, zipPath } = args;
  return {
    filename: args.filename,
    fileSize: args.fileSize,
    isImage: args.isImage,
    usage: args.usage,
    zipPath,
    readBytes: async () => {
      const file = zip.file(zipPath);
      if (!file) {
        throw new Error(`Attachment missing in ZIP: ${zipPath}`);
      }
      return file.async("arraybuffer");
    },
  };
}

function collectEntryMissing(page: ParsedPage): MissingInlineImage[] {
  const out: MissingInlineImage[] = [];
  for (const e of page.entries) out.push(...e.missingInlineImages);
  return out;
}

function basename(p: string): string {
  const cleaned = p.split("?")[0];
  const i = cleaned.lastIndexOf("/");
  return i >= 0 ? cleaned.slice(i + 1) : cleaned;
}

function stringOrNull(v: unknown): string | null {
  return typeof v === "string" && v.length > 0 ? v : null;
}

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

function decodeBase64Utf8(s: string): string {
  if (typeof atob === "function") {
    const bin = atob(s);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new TextDecoder("utf-8").decode(bytes);
  }
  const g = globalThis as { Buffer?: { from: (s: string, enc: string) => { toString: (enc: string) => string } } };
  if (g.Buffer) {
    return g.Buffer.from(s, "base64").toString("utf8");
  }
  throw new Error("No base64 decoder available");
}

function getDomParser(): DOMParser {
  const g = globalThis as { DOMParser?: typeof DOMParser };
  if (!g.DOMParser) {
    throw new Error(
      "DOMParser is not available. In a browser this is built-in; in Node use linkedom and assign globalThis.DOMParser before calling parseLabArchivesOfflineZip.",
    );
  }
  return new g.DOMParser();
}
