/**
 * THE DATA HUB TRANSFORM ENGINE VALIDATION GATE.
 *
 * Every operation this engine ships is validated against pandas before it
 * can reach a user. The reference values live in transform-golden.json,
 * generated by frontend/scripts/gen-datahub-transform-golden.py using real
 * pandas on fixed, hardcoded fixture tables.
 *
 * A test that asserts "our engine equals what our engine produced" proves
 * nothing. Every reference row here comes from pandas, never from our engine.
 *
 * This gate:
 *   - Runs executePipeline for every op variant and every chain in the golden
 *     file and asserts EXACT equality on columns, row count, and cell values.
 *   - Is environment "node" (pure logic, no DOM), so it must always pass
 *     for real (not subject to the jsdom/jest-dom caveat).
 *
 * Tolerance: numeric values are compared with a relative tolerance of 1e-9
 * to guard against floating-point representation differences between Python
 * and JS. All other values are compared with strict equality.
 *
 * House voice: no em-dashes, no emojis, no mid-sentence colons.
 */

import { describe, it, expect } from "vitest";
import { executePipeline } from "../engine";
import type { DataHubDocContent, ColumnDef, RowRecord, CellValue } from "@/lib/datahub/model/types";
import type { TransformPipeline } from "../pipeline";

// ---------------------------------------------------------------------------
// Load the golden file
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-require-imports
const GOLDEN = require("./transform-golden.json") as GoldenFile;

interface TableRef {
  columns: string[];
  rows: Record<string, unknown>[];
}

interface GoldenFile {
  provenance: Record<string, string>;
  fixtures: Record<string, TableRef>;
  references: {
    join: Record<string, TableRef>;
    join_null_keys: Record<string, TableRef>;
    join_many_many: TableRef;
    filter: Record<string, TableRef>;
    groupby: Record<string, TableRef>;
    groupby_empty_group: TableRef;
    select_drop_rename: Record<string, TableRef>;
    sort: Record<string, TableRef>;
    dedupe: Record<string, TableRef>;
    union: Record<string, TableRef>;
    chains: Record<string, TableRef>;
  };
}

// ---------------------------------------------------------------------------
// Helpers to build DataHubDocContent from fixture rows
// ---------------------------------------------------------------------------

function fixtureContent(name: string): DataHubDocContent {
  const fix = GOLDEN.fixtures[name];
  if (!fix) throw new Error(`fixture "${name}" not found in golden file`);

  const columns: ColumnDef[] = fix.columns.map((colName, i) => {
    // Infer type from first non-null value.
    const firstNonNull = fix.rows.map((r) => r[colName]).find(
      (v) => v !== null && v !== undefined,
    );
    const isNumeric =
      typeof firstNonNull === "number" ||
      (typeof firstNonNull === "string" && Number.isFinite(Number(firstNonNull)));
    return {
      id: `col-${i + 1}`,
      name: colName,
      role: "y" as const,
      dataType: isNumeric ? ("number" as const) : ("text" as const),
    };
  });

  const colNameToId = new Map(columns.map((c) => [c.name, c.id]));

  const rows: RowRecord[] = fix.rows.map((row, ri) => {
    const cells: Record<string, CellValue> = {};
    for (const col of columns) {
      const v = row[col.name] as CellValue;
      cells[col.id] = v !== undefined ? v : null;
    }
    return { id: `row-${ri + 1}`, cells };
  });

  return {
    meta: {
      id: name,
      name,
      project_ids: [],
      folder_path: null,
      table_type: "column" as const,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    columns,
    rows,
    analyses: [],
    plots: [],
  };
}

// ---------------------------------------------------------------------------
// Assertion helper
// ---------------------------------------------------------------------------

const NUM_TOLERANCE = 1e-9;

function assertMatchesRef(
  label: string,
  result: ReturnType<typeof executePipeline>,
  ref: TableRef,
) {
  if ("error" in result) {
    throw new Error(`${label}: engine returned error: ${result.error}`);
  }
  const content = result.content;

  // Column names match (order matters).
  const resultCols = content.columns.map((c) => c.name);
  expect(resultCols, `${label}: column names`).toEqual(ref.columns);

  // Row count matches.
  expect(
    content.rows.length,
    `${label}: row count (got ${content.rows.length}, want ${ref.rows.length})`,
  ).toBe(ref.rows.length);

  // Cell values match row-by-row.
  const colIdToName = new Map(content.columns.map((c) => [c.id, c.name]));
  for (let ri = 0; ri < ref.rows.length; ri++) {
    const expectedRow = ref.rows[ri];
    const actualCells = content.rows[ri].cells;

    for (const colDef of content.columns) {
      const colName = colDef.name;
      const actual = actualCells[colDef.id] ?? null;
      const expected = (expectedRow[colName] as CellValue) ?? null;

      if (expected === null && actual === null) continue;
      if (expected === null || actual === null) {
        expect(
          actual,
          `${label} row[${ri}] col "${colName}": expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`,
        ).toBe(expected);
        continue;
      }

      if (typeof expected === "number" && typeof actual === "number") {
        if (expected === 0) {
          expect(actual, `${label} row[${ri}] col "${colName}"`).toBe(0);
        } else {
          const relDiff = Math.abs((actual - expected) / expected);
          expect(
            relDiff,
            `${label} row[${ri}] col "${colName}": expected ${expected}, got ${actual}, rel diff ${relDiff}`,
          ).toBeLessThanOrEqual(NUM_TOLERANCE);
        }
      } else if (typeof expected === "number" && typeof actual === "string") {
        // Engine may store numeric values as strings from concat/text columns.
        const actualNum = Number(actual);
        if (Number.isFinite(actualNum)) {
          const relDiff = expected === 0 ? Math.abs(actualNum) : Math.abs((actualNum - expected) / expected);
          expect(relDiff, `${label} row[${ri}] col "${colName}" (string->number): expected ${expected}, got ${actual}`).toBeLessThanOrEqual(NUM_TOLERANCE);
        } else {
          expect(actual, `${label} row[${ri}] col "${colName}"`).toBe(String(expected));
        }
      } else {
        expect(
          String(actual),
          `${label} row[${ri}] col "${colName}"`,
        ).toBe(String(expected));
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Fixture contents (loaded once)
// ---------------------------------------------------------------------------

const TABLE_A = fixtureContent("TABLE_A");
const TABLE_B = fixtureContent("TABLE_B");
const TABLE_C = fixtureContent("TABLE_C");
const TABLE_DUPES = fixtureContent("TABLE_DUPES");
const TABLE_NULL_KEYS = fixtureContent("TABLE_NULL_KEYS");
const TABLE_NULL_KEYS_B = fixtureContent("TABLE_NULL_KEYS_B");
const TABLE_MM_LEFT = fixtureContent("TABLE_MM_LEFT");
const TABLE_MM_RIGHT = fixtureContent("TABLE_MM_RIGHT");

// Helper to build a sources map for multi-table ops.
function sources(...pairs: [string, DataHubDocContent][]): Map<string, DataHubDocContent> {
  return new Map(pairs);
}

// ---------------------------------------------------------------------------
// Join tests
// ---------------------------------------------------------------------------

describe("join (pandas-validated)", () => {
  for (const how of ["inner", "left", "right", "outer"] as const) {
    it(`${how} join on sample_id`, () => {
      const pipeline: TransformPipeline = {
        ops: [{ kind: "join", rightRef: "TABLE_B", on: ["sample_id"], how }],
      };
      const result = executePipeline(TABLE_A, pipeline, sources(["TABLE_B", TABLE_B]));
      assertMatchesRef(`join.${how}`, result, GOLDEN.references.join[how]);
    });
  }

  it("inner join with null key values (null-key rows are dropped)", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "join", rightRef: "TABLE_NULL_KEYS_B", on: ["id"], how: "inner" }],
    };
    const result = executePipeline(TABLE_NULL_KEYS, pipeline, sources(["TABLE_NULL_KEYS_B", TABLE_NULL_KEYS_B]));
    assertMatchesRef("join_null_keys.inner", result, GOLDEN.references.join_null_keys["inner"]);
  });

  it("left join with null key values in left table", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "join", rightRef: "TABLE_NULL_KEYS_B", on: ["id"], how: "left" }],
    };
    const result = executePipeline(TABLE_NULL_KEYS, pipeline, sources(["TABLE_NULL_KEYS_B", TABLE_NULL_KEYS_B]));
    assertMatchesRef("join_null_keys.left", result, GOLDEN.references.join_null_keys["left"]);
  });

  it("outer join with null key values", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "join", rightRef: "TABLE_NULL_KEYS_B", on: ["id"], how: "outer" }],
    };
    const result = executePipeline(TABLE_NULL_KEYS, pipeline, sources(["TABLE_NULL_KEYS_B", TABLE_NULL_KEYS_B]));
    assertMatchesRef("join_null_keys.outer", result, GOLDEN.references.join_null_keys["outer"]);
  });

  it("many-to-many inner join produces cross product", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "join", rightRef: "TABLE_MM_RIGHT", on: ["k"], how: "inner" }],
    };
    const result = executePipeline(TABLE_MM_LEFT, pipeline, sources(["TABLE_MM_RIGHT", TABLE_MM_RIGHT]));
    assertMatchesRef("join_many_many", result, GOLDEN.references.join_many_many);
  });

  it("returns error when key column is missing", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "join", rightRef: "TABLE_B", on: ["nonexistent"], how: "inner" }],
    };
    const result = executePipeline(TABLE_A, pipeline, sources(["TABLE_B", TABLE_B]));
    expect("error" in result).toBe(true);
  });

  it("returns error when source table is missing", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "join", rightRef: "TABLE_MISSING", on: ["sample_id"], how: "inner" }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    expect("error" in result).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Filter tests
// ---------------------------------------------------------------------------

describe("filter (pandas-validated)", () => {
  it("eq: strain == WT", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "filter", node: { type: "condition", condition: { column: "strain", op: "eq", value: "WT" } } }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.strain_eq_WT", result, GOLDEN.references.filter["strain_eq_WT"]);
  });

  it("gt: expression > 2.0 (null values are not > 2.0)", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "filter", node: { type: "condition", condition: { column: "expression", op: "gt", value: 2.0 } } }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.expression_gt_2", result, GOLDEN.references.filter["expression_gt_2"]);
  });

  it("contains: strain contains 'mut'", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "filter", node: { type: "condition", condition: { column: "strain", op: "contains", value: "mut" } } }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.strain_contains_mut", result, GOLDEN.references.filter["strain_contains_mut"]);
  });

  it("is_empty: expression is null", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "filter", node: { type: "condition", condition: { column: "expression", op: "is_empty" } } }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.expression_is_empty", result, GOLDEN.references.filter["expression_is_empty"]);
  });

  it("in: strain in [WT, mutA]", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "filter", node: { type: "condition", condition: { column: "strain", op: "in", value: ["WT", "mutA"] } } }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.strain_in_WT_mutA", result, GOLDEN.references.filter["strain_in_WT_mutA"]);
  });

  it("AND: strain == mutA AND expression > 2.0", () => {
    const pipeline: TransformPipeline = {
      ops: [{
        kind: "filter",
        node: {
          type: "and",
          children: [
            { type: "condition", condition: { column: "strain", op: "eq", value: "mutA" } },
            { type: "condition", condition: { column: "expression", op: "gt", value: 2.0 } },
          ],
        },
      }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.strain_mutA_and_expr_gt_2", result, GOLDEN.references.filter["strain_mutA_and_expr_gt_2"]);
  });

  it("NOT: not (strain == WT)", () => {
    const pipeline: TransformPipeline = {
      ops: [{
        kind: "filter",
        node: {
          type: "not",
          child: { type: "condition", condition: { column: "strain", op: "eq", value: "WT" } },
        },
      }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("filter.not_strain_WT", result, GOLDEN.references.filter["not_strain_WT"]);
  });
});

// ---------------------------------------------------------------------------
// GroupBy tests
// ---------------------------------------------------------------------------

describe("groupby (pandas-validated)", () => {
  for (const func of ["mean", "sum", "count", "min", "max", "median", "sd", "first", "nunique", "concat"] as const) {
    it(`groupby strain, ${func} of expression`, () => {
      const pipeline: TransformPipeline = {
        ops: [{
          kind: "groupby",
          by: ["strain"],
          aggregations: [{ column: "expression", func, outputName: `expression_${func}` }],
        }],
      };
      const result = executePipeline(TABLE_A, pipeline, new Map());
      assertMatchesRef(`groupby.expression_${func}`, result, GOLDEN.references.groupby[`expression_${func}`]);
    });
  }

  it("groupby with all-null group: null mean (matches pandas NaN->null)", () => {
    // Build a tiny table with an all-null group.
    const rows: Record<string, CellValue>[] = [
      { group: "A", val: 1.0 },
      { group: "A", val: 2.0 },
      { group: "B", val: null },
      { group: "B", val: null },
    ];
    const colA: ColumnDef = { id: "c1", name: "group", role: "y", dataType: "text" };
    const colB: ColumnDef = { id: "c2", name: "val", role: "y", dataType: "number" };
    const content: DataHubDocContent = {
      meta: { id: "t", name: "t", project_ids: [], folder_path: null, table_type: "column", created_at: "2026-01-01T00:00:00.000Z" },
      columns: [colA, colB],
      rows: rows.map((r, i) => ({ id: `r${i}`, cells: { c1: r["group"], c2: r["val"] } })),
      analyses: [],
      plots: [],
    };
    const pipeline: TransformPipeline = {
      ops: [{ kind: "groupby", by: ["group"], aggregations: [{ column: "val", func: "mean", outputName: "val_mean" }] }],
    };
    const result = executePipeline(content, pipeline, new Map());
    assertMatchesRef("groupby_empty_group", result, GOLDEN.references.groupby_empty_group);
  });
});

// ---------------------------------------------------------------------------
// Select / Drop / Rename tests
// ---------------------------------------------------------------------------

describe("select / drop / rename (pandas-validated)", () => {
  it("select: keep sample_id and expression", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "select", columns: ["sample_id", "expression"] }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("select_drop_rename.select_sid_expr", result, GOLDEN.references.select_drop_rename["select_sid_expr"]);
  });

  it("drop: remove expression column", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "drop", columns: ["expression"] }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("select_drop_rename.drop_expression", result, GOLDEN.references.select_drop_rename["drop_expression"]);
  });

  it("rename: expression->expr_value, strain->genotype", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "rename", mapping: { expression: "expr_value", strain: "genotype" } }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("select_drop_rename.rename_expr_strain", result, GOLDEN.references.select_drop_rename["rename_expr_strain"]);
  });

  it("select returns error on unknown column", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "select", columns: ["nonexistent"] }],
    };
    expect("error" in executePipeline(TABLE_A, pipeline, new Map())).toBe(true);
  });

  it("drop returns error on unknown column", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "drop", columns: ["nonexistent"] }],
    };
    expect("error" in executePipeline(TABLE_A, pipeline, new Map())).toBe(true);
  });

  it("rename returns error on unknown column", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "rename", mapping: { nonexistent: "x" } }],
    };
    expect("error" in executePipeline(TABLE_A, pipeline, new Map())).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Sort tests
// ---------------------------------------------------------------------------

describe("sort (pandas-validated)", () => {
  it("sort by expression asc (nulls last)", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "sort", by: [{ column: "expression", direction: "asc", nulls: "last" }] }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("sort.expression_asc", result, GOLDEN.references.sort["expression_asc"]);
  });

  it("sort by expression desc (nulls first)", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "sort", by: [{ column: "expression", direction: "desc", nulls: "first" }] }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("sort.expression_desc", result, GOLDEN.references.sort["expression_desc"]);
  });

  it("sort by strain asc, then expression desc (multi-key)", () => {
    const pipeline: TransformPipeline = {
      ops: [{
        kind: "sort",
        by: [
          { column: "strain", direction: "asc", nulls: "last" },
          { column: "expression", direction: "desc", nulls: "last" },
        ],
      }],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("sort.strain_asc_expr_desc", result, GOLDEN.references.sort["strain_asc_expr_desc"]);
  });

  it("sort returns error on unknown column", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "sort", by: [{ column: "nonexistent", direction: "asc" }] }],
    };
    expect("error" in executePipeline(TABLE_A, pipeline, new Map())).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Dedupe tests
// ---------------------------------------------------------------------------

describe("dedupe (pandas-validated)", () => {
  it("dedupe all columns, keep first", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "dedupe", keep: "first" }],
    };
    const result = executePipeline(TABLE_DUPES, pipeline, new Map());
    assertMatchesRef("dedupe.all_first", result, GOLDEN.references.dedupe["all_first"]);
  });

  it("dedupe all columns, keep last", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "dedupe", keep: "last" }],
    };
    const result = executePipeline(TABLE_DUPES, pipeline, new Map());
    assertMatchesRef("dedupe.all_last", result, GOLDEN.references.dedupe["all_last"]);
  });

  it("dedupe by key subset, keep first", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "dedupe", subset: ["key"], keep: "first" }],
    };
    const result = executePipeline(TABLE_DUPES, pipeline, new Map());
    assertMatchesRef("dedupe.key_subset_first", result, GOLDEN.references.dedupe["key_subset_first"]);
  });

  it("dedupe by key subset, keep last", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "dedupe", subset: ["key"], keep: "last" }],
    };
    const result = executePipeline(TABLE_DUPES, pipeline, new Map());
    assertMatchesRef("dedupe.key_subset_last", result, GOLDEN.references.dedupe["key_subset_last"]);
  });
});

// ---------------------------------------------------------------------------
// Union tests
// ---------------------------------------------------------------------------

describe("union (pandas-validated)", () => {
  it("union same-schema tables stacks rows", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "union", otherRef: "TABLE_C" }],
    };
    const result = executePipeline(TABLE_A, pipeline, sources(["TABLE_C", TABLE_C]));
    assertMatchesRef("union.same_schema", result, GOLDEN.references.union["same_schema"]);
  });

  it("union with extra column in second table fills nulls", () => {
    // Build a table with only sample_id and batch columns.
    const extraContent: DataHubDocContent = {
      meta: { id: "extra", name: "extra", project_ids: [], folder_path: null, table_type: "column", created_at: "2026-01-01T00:00:00.000Z" },
      columns: [
        { id: "c1", name: "sample_id", role: "y", dataType: "text" },
        { id: "c2", name: "batch", role: "y", dataType: "text" },
      ],
      rows: [{ id: "r1", cells: { c1: "SX", c2: "B2" } }],
      analyses: [],
      plots: [],
    };
    const pipeline: TransformPipeline = {
      ops: [{ kind: "union", otherRef: "extra" }],
    };
    const result = executePipeline(TABLE_A, pipeline, sources(["extra", extraContent]));
    assertMatchesRef("union.extra_column", result, GOLDEN.references.union["extra_column"]);
  });

  it("returns error when other table is missing", () => {
    const pipeline: TransformPipeline = {
      ops: [{ kind: "union", otherRef: "MISSING" }],
    };
    expect("error" in executePipeline(TABLE_A, pipeline, new Map())).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Chain tests
// ---------------------------------------------------------------------------

describe("chained pipelines (pandas-validated)", () => {
  it("join -> filter -> groupby", () => {
    const pipeline: TransformPipeline = {
      ops: [
        { kind: "join", rightRef: "TABLE_B", on: ["sample_id"], how: "inner" },
        { kind: "filter", node: { type: "condition", condition: { column: "expression", op: "gt", value: 1.0 } } },
        { kind: "groupby", by: ["strain"], aggregations: [{ column: "expression", func: "mean", outputName: "expression_mean" }] },
      ],
    };
    const result = executePipeline(TABLE_A, pipeline, sources(["TABLE_B", TABLE_B]));
    assertMatchesRef("chains.join_filter_groupby", result, GOLDEN.references.chains["join_filter_groupby"]);
  });

  it("left join -> select -> sort", () => {
    const pipeline: TransformPipeline = {
      ops: [
        { kind: "join", rightRef: "TABLE_B", on: ["sample_id"], how: "left" },
        { kind: "select", columns: ["sample_id", "strain", "expression", "condition"] },
        { kind: "sort", by: [{ column: "expression", direction: "asc", nulls: "last" }] },
      ],
    };
    const result = executePipeline(TABLE_A, pipeline, sources(["TABLE_B", TABLE_B]));
    assertMatchesRef("chains.left_join_select_sort", result, GOLDEN.references.chains["left_join_select_sort"]);
  });

  it("filter -> rename -> dedupe", () => {
    const pipeline: TransformPipeline = {
      ops: [
        { kind: "filter", node: { type: "condition", condition: { column: "strain", op: "in", value: ["WT", "mutA"] } } },
        { kind: "rename", mapping: { strain: "genotype" } },
        { kind: "dedupe", subset: ["genotype"], keep: "first" },
      ],
    };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    assertMatchesRef("chains.filter_rename_dedupe", result, GOLDEN.references.chains["filter_rename_dedupe"]);
  });
});

// ---------------------------------------------------------------------------
// Empty pipeline
// ---------------------------------------------------------------------------

describe("empty pipeline", () => {
  it("returns the primary table unchanged (same rows and columns)", () => {
    const pipeline: TransformPipeline = { ops: [] };
    const result = executePipeline(TABLE_A, pipeline, new Map());
    if ("error" in result) throw new Error(result.error);
    expect(result.content.columns.map((c) => c.name)).toEqual(TABLE_A.columns.map((c) => c.name));
    expect(result.content.rows.length).toBe(TABLE_A.rows.length);
  });
});
