/**
 * Mobile wiki data layer.
 *
 * Loads the wiki content bundle (generated by scripts/build-wiki-content.mjs).
 * Primary path: bundled JSON imported at build time (works fully offline).
 * Bonus path: if EXPO_PUBLIC_WIKI_CONTENT_URL is set, fetch + AsyncStorage
 * cache so wiki updates reach the app without a store release.
 *
 * House style: no em-dashes, no emojis, no mid-sentence colons.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';

// Bundled JSON is the always-available source of truth. The import resolves
// at Metro build time, so it works offline and does not require a network call.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const BUNDLED: WikiContent = require('@/assets/wiki-content.json');

// Optional runtime-fetch URL. Set EXPO_PUBLIC_WIKI_CONTENT_URL in .env to
// override the bundled data with a freshly fetched version (e.g. from the
// Next.js public directory or a CDN). Leave unset to always use the bundle.
const REMOTE_URL: string | undefined = process.env.EXPO_PUBLIC_WIKI_CONTENT_URL;

const CACHE_KEY = 'wiki:content:v1';

/* ─────────────────────── public types ──────────────────────────────────── */

export type BlockKind = 'heading' | 'paragraph' | 'list' | 'callout' | 'code' | 'image';

export interface HeadingBlock {
  kind: 'heading';
  level: 2 | 3 | 4;
  text: string;
}

export interface ParagraphBlock {
  kind: 'paragraph';
  text: string;
}

export interface ListBlock {
  kind: 'list';
  ordered: boolean;
  items: string[];
}

export interface CalloutBlock {
  kind: 'callout';
  variant: string;
  title: string | null;
  text: string;
}

export interface CodeBlock {
  kind: 'code';
  text: string;
}

export interface ImageBlock {
  kind: 'image';
  src: string;
  alt: string;
  caption: string | null;
}

export type WikiBlock =
  | HeadingBlock
  | ParagraphBlock
  | ListBlock
  | CalloutBlock
  | CodeBlock
  | ImageBlock;

export interface WikiEntry {
  slug: string;
  href: string;
  section: string;
  title: string;
  summary: string | null;
  blurb: string | null;
  breadcrumbs: string[];
  blocks: WikiBlock[];
}

export interface WikiSection {
  id: string;
  label: string;
  blurb: string | null;
}

export interface WikiContent {
  generatedAt: string;
  pageCount: number;
  sections: WikiSection[];
  entries: WikiEntry[];
}

/* ─────────────────────── search types (ported from frontend/src/lib/wiki/search.ts) */

export interface WikiSearchHit {
  entry: WikiEntry;
  score: number;
  matchKind: 'title' | 'heading' | 'body';
  /** Snippet text around the match (title itself for title matches). */
  snippetText: string;
  /** Offset of the match within snippetText. */
  snippetOffset: number;
  /** Length of the matched substring. */
  snippetLength: number;
}

/* ─────────────────────── content loading ───────────────────────────────── */

let _cached: WikiContent | null = null;

/**
 * Load the wiki content. Resolves immediately from memory if already loaded.
 * On first call:
 *   1. Returns the bundled copy synchronously (wrapped in a resolved promise)
 *      so the UI can render without awaiting.
 *   2. If EXPO_PUBLIC_WIKI_CONTENT_URL is set, attempts to fetch a fresher
 *      copy from the network (best-effort). On success, stores in AsyncStorage
 *      so the next launch uses the fresher copy even offline. If the fetch
 *      fails, the bundled copy continues to be used.
 */
export async function loadWikiContent(): Promise<WikiContent> {
  if (_cached) return _cached;

  // Check AsyncStorage for a previously fetched fresher copy.
  if (REMOTE_URL) {
    try {
      const stored = await AsyncStorage.getItem(CACHE_KEY);
      if (stored) {
        const parsed: WikiContent = JSON.parse(stored);
        // Accept stored copy only if it is newer than the bundle.
        if (new Date(parsed.generatedAt) > new Date(BUNDLED.generatedAt)) {
          _cached = parsed;
          // Kick off a background refresh for next launch.
          void fetchAndCache(REMOTE_URL);
          return _cached;
        }
      }
    } catch {
      // AsyncStorage unavailable or corrupted; fall through to bundle.
    }
    // Fire background fetch; the current call still returns the bundle.
    void fetchAndCache(REMOTE_URL);
  }

  _cached = BUNDLED;
  return _cached;
}

async function fetchAndCache(url: string): Promise<void> {
  try {
    const res = await fetch(url);
    if (!res.ok) return;
    const text = await res.text();
    const data: WikiContent = JSON.parse(text);
    if (!data.entries || !Array.isArray(data.entries)) return;
    await AsyncStorage.setItem(CACHE_KEY, text);
    // Update in-memory cache if the fetched copy is fresher.
    if (!_cached || new Date(data.generatedAt) > new Date(_cached.generatedAt)) {
      _cached = data;
    }
  } catch {
    // Network error, JSON parse failure, storage full -- all silently swallowed.
  }
}

/* ─────────────────────── synchronous bundled accessor ──────────────────── */

/** Returns the bundled content immediately without awaiting AsyncStorage.
 *  Safe to call during render; always returns something. */
export function getBundledContent(): WikiContent {
  return BUNDLED;
}

/* ─────────────────────── search (ported from frontend search.ts) ────────── */

const TITLE_SCORE = 1000;
const HEADING_SCORE = 100;
const BODY_SCORE = 10;
const WORD_BOUNDARY_BONUS = 50;
const EARLY_POSITION_BONUS = 10;
const PHRASE_BONUS_MULTIPLIER = 1.5;
const CONTEXT_CHARS = 60;

function ciIndexOf(haystack: string, needle: string): number {
  if (!needle) return -1;
  return haystack.toLowerCase().indexOf(needle.toLowerCase());
}

function isWordBoundary(haystack: string, offset: number): boolean {
  if (offset === 0) return true;
  const prev = haystack[offset - 1];
  return /[\s\-_/.,;:()[\]{}'"]/.test(prev);
}

function scoreOne(
  haystack: string,
  needle: string,
  baseScore: number,
): { score: number; offset: number } | null {
  const offset = ciIndexOf(haystack, needle);
  if (offset === -1) return null;
  let score = baseScore;
  if (isWordBoundary(haystack, offset)) score += WORD_BOUNDARY_BONUS;
  if (offset < 16) score += EARLY_POSITION_BONUS;
  return { score, offset };
}

function tokenize(query: string): string[] {
  return query
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter((t) => t.length > 0);
}

/** Extract plain-text snippets from blocks for body search. */
function entryBodySnippets(entry: WikiEntry): string[] {
  const snippets: string[] = [];
  for (const block of entry.blocks) {
    if (block.kind === 'paragraph') snippets.push(block.text);
    else if (block.kind === 'list') snippets.push(...block.items);
    else if (block.kind === 'callout') {
      if (block.title) snippets.push(block.title);
      if (block.text) snippets.push(block.text);
    }
    else if (block.kind === 'image') {
      if (block.alt) snippets.push(block.alt);
      if (block.caption) snippets.push(block.caption);
    }
  }
  if (entry.summary) snippets.unshift(entry.summary);
  return snippets;
}

/** Extract heading strings from blocks. */
function entryHeadings(entry: WikiEntry): string[] {
  const out: string[] = [];
  for (const block of entry.blocks) {
    if (block.kind === 'heading') out.push(block.text);
    else if (block.kind === 'callout' && block.title) out.push(block.title);
  }
  return out;
}

function buildSnippetAround(
  text: string,
  offset: number,
  matchLength: number,
): { snippetText: string; snippetOffset: number; snippetLength: number } {
  const start = Math.max(0, offset - CONTEXT_CHARS);
  const end = Math.min(text.length, offset + matchLength + CONTEXT_CHARS);
  const prefix = start > 0 ? '...' : '';
  const suffix = end < text.length ? '...' : '';
  const snippetText = prefix + text.slice(start, end) + suffix;
  const snippetOffset = (start > 0 ? 3 : 0) + (offset - start);
  const snippetLength = Math.max(1, Math.min(matchLength, snippetText.length - snippetOffset));
  return { snippetText, snippetOffset, snippetLength };
}

function matchEntry(entry: WikiEntry, query: string): WikiSearchHit | null {
  const tokens = tokenize(query);
  if (tokens.length === 0) return null;
  const full = query.trim();

  // Title
  {
    const phrase = scoreOne(entry.title, full, TITLE_SCORE);
    if (phrase) {
      const allHit = tokens.every((t) => ciIndexOf(entry.title, t) !== -1);
      const score = allHit ? phrase.score * PHRASE_BONUS_MULTIPLIER : phrase.score;
      return {
        entry, score, matchKind: 'title',
        snippetText: entry.title,
        snippetOffset: phrase.offset,
        snippetLength: Math.max(1, full.length),
      };
    }
    if (tokens.every((t) => ciIndexOf(entry.title, t) !== -1)) {
      return {
        entry, score: TITLE_SCORE * 0.9, matchKind: 'title',
        snippetText: entry.title, snippetOffset: 0,
        snippetLength: Math.max(1, tokens[0].length),
      };
    }
  }

  // Headings
  let bestHeading: WikiSearchHit | null = null;
  for (const heading of entryHeadings(entry)) {
    const phrase = scoreOne(heading, full, HEADING_SCORE);
    if (phrase) {
      const allHit = tokens.every((t) => ciIndexOf(heading, t) !== -1);
      const score = allHit ? phrase.score * PHRASE_BONUS_MULTIPLIER : phrase.score;
      if (!bestHeading || score > bestHeading.score) {
        const { snippetText, snippetOffset, snippetLength } = buildSnippetAround(heading, phrase.offset, full.length);
        bestHeading = { entry, score, matchKind: 'heading', snippetText, snippetOffset, snippetLength };
      }
    } else if (tokens.every((t) => ciIndexOf(heading, t) !== -1)) {
      const firstHit = tokens.map((t) => ({ t, off: ciIndexOf(heading, t) })).find((x) => x.off !== -1);
      const score = HEADING_SCORE * 0.9;
      if (!bestHeading || score > bestHeading.score) {
        const off = firstHit?.off ?? 0;
        const { snippetText, snippetOffset, snippetLength } = buildSnippetAround(heading, off, firstHit?.t.length ?? tokens[0].length);
        bestHeading = { entry, score, matchKind: 'heading', snippetText, snippetOffset, snippetLength };
      }
    }
  }
  if (bestHeading) return bestHeading;

  // Body
  let bestBody: WikiSearchHit | null = null;
  for (const body of entryBodySnippets(entry)) {
    const phrase = scoreOne(body, full, BODY_SCORE);
    if (phrase) {
      const allHit = tokens.every((t) => ciIndexOf(body, t) !== -1);
      const score = allHit ? phrase.score * PHRASE_BONUS_MULTIPLIER : phrase.score;
      if (!bestBody || score > bestBody.score) {
        const { snippetText, snippetOffset, snippetLength } = buildSnippetAround(body, phrase.offset, full.length);
        bestBody = { entry, score, matchKind: 'body', snippetText, snippetOffset, snippetLength };
      }
    } else if (tokens.every((t) => ciIndexOf(body, t) !== -1)) {
      const firstHit = tokens.map((t) => ({ t, off: ciIndexOf(body, t) })).find((x) => x.off !== -1);
      const score = BODY_SCORE * 0.9;
      if (!bestBody || score > bestBody.score) {
        const off = firstHit?.off ?? 0;
        const { snippetText, snippetOffset, snippetLength } = buildSnippetAround(body, off, firstHit?.t.length ?? tokens[0].length);
        bestBody = { entry, score, matchKind: 'body', snippetText, snippetOffset, snippetLength };
      }
    }
  }
  return bestBody;
}

/**
 * Search the wiki, returning ranked hits. Results are sorted by score
 * descending, capped at maxResults. Query must be >= 2 chars.
 */
export function searchWiki(
  content: WikiContent,
  query: string,
  maxResults = 25,
): WikiSearchHit[] {
  const trimmed = query.trim();
  if (trimmed.length < 2) return [];
  const hits: WikiSearchHit[] = [];
  for (const entry of content.entries) {
    const hit = matchEntry(entry, trimmed);
    if (hit) hits.push(hit);
  }
  hits.sort((a, b) => b.score - a.score);
  return hits.slice(0, maxResults);
}

/** Group search hits by section for display. */
export function groupSearchHits(
  hits: WikiSearchHit[],
  sections: WikiSection[],
): Array<{ section: WikiSection; hits: WikiSearchHit[] }> {
  const byId = new Map<string, WikiSearchHit[]>();
  for (const s of sections) byId.set(s.id, []);
  for (const hit of hits) {
    const bucket = byId.get(hit.entry.section);
    if (bucket) bucket.push(hit);
    else byId.set(hit.entry.section, [hit]);
  }
  const groups: Array<{ section: WikiSection; hits: WikiSearchHit[] }> = [];
  for (const s of sections) {
    const sectionHits = byId.get(s.id) ?? [];
    if (sectionHits.length > 0) groups.push({ section: s, hits: sectionHits });
  }
  // Orphan sections not in the predefined list.
  for (const [id, sectionHits] of byId) {
    if (sectionHits.length === 0) continue;
    if (groups.find((g) => g.section.id === id)) continue;
    groups.push({ section: { id, label: id, blurb: null }, hits: sectionHits });
  }
  return groups;
}

/** Return the entries for a given section id, in nav order. */
export function entriesForSection(content: WikiContent, sectionId: string): WikiEntry[] {
  return content.entries.filter((e) => e.section === sectionId);
}

/** Look up a single entry by slug. */
export function entryBySlug(content: WikiContent, slug: string): WikiEntry | null {
  return content.entries.find((e) => e.slug === slug) ?? null;
}
